var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/elite-studio/operations/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2598f68a._.js")
R.c("server/chunks/ssr/9e883_next_dist_3aff4f06._.js")
R.c("server/chunks/ssr/frontend_c77c58af._.js")
R.c("server/chunks/ssr/[root-of-the-server]__839066b2._.js")
R.c("server/chunks/ssr/9e883_next_dist_596e9b5c._.js")
R.c("server/chunks/ssr/9e883_13c1491f._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_global-error_c00881b3.js")
R.c("server/chunks/ssr/[root-of-the-server]__59cf3f7c._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_34a976ba._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_forbidden_520cb951.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_unauthorized_62f331ea.js")
R.c("server/chunks/ssr/frontend_app_admin_layout_tsx_73881dee._.js")
R.c("server/chunks/ssr/frontend_app_admin_elite-studio_layout_tsx_1c723eca._.js")
R.c("server/chunks/ssr/ceffb__next-internal_server_app_admin_elite-studio_operations_page_actions_e36ea417.js")
R.m(997742)
module.exports=R.m(997742).exports
