"""Catalog — Single source of truth loader for SkyyRose product data.

Reads `assets/product-masters/catalog.yaml` (generated by
`scripts/generate_catalog.py`) and exposes a typed, queryable API:

    from skyyrose.elite_studio.catalog import Catalog

    cat = Catalog.load()
    p = cat.require("sg-013")
    print(p.series)            # 'Mint & Lavender'
    print(p.branding_summary)  # 'Lavender rose embroidered logo centered...'

    members = cat.products_in_series("Mint & Lavender")
    # [sg-006, sg-013, sg-014]

    alias_hit = cat.resolve_sku("br-d02")
    # Returns the ProductEntry for br-008 (SF Inspired Jersey)

Readers expected to consume this module:
  - Prompt generators (Gemini / FLUX) — branding_summary, variants, color_spec
  - Vision test (scripts/vision_test_registry.py) — alias + prefix resolution
  - Fidelity gate (skyyrose/elite_studio/fidelity.py) — color_spec + text_spec
  - Sync script (scripts/sync_manifest_from_catalog.py) — derives manifest.json
  - Copywriter skills — name, price, branding, variants
  - Compositor Stage 7 — master path + hash (via manifest.json for now)

catalog.yaml is the ONLY editable source; manifest.json is a derived artifact.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as _e:  # pragma: no cover
    raise ImportError(
        "PyYAML is required to load catalog.yaml. Install with `pip install pyyaml`."
    ) from _e

from .validation import (
    IntegrityError,
    Violation,
    validate_enum,
    validate_hex_color,
    validate_non_negative,
    validate_not_empty,
    validate_sku_format,
)

_ENV_CATALOG_PATH = "SKYYROSE_CATALOG_PATH"

PRODUCT_STATUS = {"draft", "pre-order", "live", "retired"}
MASTER_SOURCE = {"pending", "photograph", "techflat", "design"}


def default_catalog_path() -> Path:
    """Return the canonical catalog.yaml path (env-overridable)."""
    override = os.getenv(_ENV_CATALOG_PATH)
    if override:
        return Path(override)
    # skyyrose/elite_studio/catalog.py → climb 2 to <repo_root>
    repo_root = Path(__file__).resolve().parents[2]
    return repo_root / "assets" / "product-masters" / "catalog.yaml"


# ─── Dataclasses ─────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class ProductEntry:
    sku: str
    name: str
    collection: str
    price_usd: float
    status: str  # 'draft' | 'pre-order' | 'live' | 'retired'
    branding_summary: str
    series: str | None
    aliases: tuple[str, ...]
    filename_patterns: tuple[str, ...]
    color_spec: dict[str, Any]
    text_spec: tuple[str, ...]
    variants: tuple[dict, ...]
    master: dict[str, Any]
    source_files: tuple[str, ...]
    ai_renders: tuple[str, ...]
    review_flags: tuple[str, ...]
    notes: str
    limited_pieces: int | None = None
    retirement_note: str | None = None

    def __post_init__(self) -> None:
        # Structural validation — raise loud, not silent
        p = f"products[{self.sku!r}]"
        validate_sku_format(self.sku, f"{p}.sku")
        validate_not_empty(self.name, f"{p}.name")
        validate_not_empty(self.collection, f"{p}.collection")
        validate_enum(self.status, PRODUCT_STATUS, f"{p}.status")
        validate_non_negative(self.price_usd, f"{p}.price_usd")

        # color_spec.primary required + hex-format
        primary = (self.color_spec or {}).get("primary")
        if primary is not None:  # allow null for kids (palette varies)
            validate_hex_color(primary, f"{p}.color_spec.primary")
        for i, accent in enumerate((self.color_spec or {}).get("accents") or []):
            validate_hex_color(accent, f"{p}.color_spec.accents[{i}]")

        # Aliases must be valid SKU format (they're legacy SKU codes)
        for i, alias in enumerate(self.aliases):
            validate_sku_format(alias, f"{p}.aliases[{i}]")

        # Master.source must be valid enum if present
        master_source = (self.master or {}).get("source")
        if master_source is not None:
            validate_enum(master_source, MASTER_SOURCE, f"{p}.master.source")

        # limited_pieces: positive int if set
        if self.limited_pieces is not None:
            if not isinstance(self.limited_pieces, int) or self.limited_pieces < 1:
                raise ValueError(
                    f"{p}.limited_pieces: must be a positive int or null, got {self.limited_pieces!r}"
                )

    @property
    def is_active(self) -> bool:
        return self.status != "retired"

    @property
    def is_locked(self) -> bool:
        m = self.master or {}
        return bool(m.get("path")) and m.get("hash") is not None

    @property
    def all_filename_keys(self) -> tuple[str, ...]:
        """SKU + aliases — all prefix keys this product answers to."""
        return (self.sku,) + tuple(self.aliases)


@dataclass(frozen=True)
class SeriesEntry:
    name: str
    collection: str
    description: str
    skus: tuple[str, ...]
    lookbook_images: tuple[str, ...]


@dataclass(frozen=True)
class Catalog:
    version: int
    generated_at: str
    collections: dict[str, Any]
    catalog_rules: dict[str, Any]
    series_by_name: dict[str, SeriesEntry]
    products_by_sku: dict[str, ProductEntry]
    unclaimed_legacy_files: dict[str, Any]
    orphan_brand_files: dict[str, Any]
    violations: tuple[Violation, ...] = ()

    # ─── Loading ────────────────────────────────────────────────────────

    @classmethod
    def load(cls, path: Path | str | None = None, *, strict: bool = False) -> Catalog:
        """Load catalog.yaml. Structural errors always raise ValueError (via __post_init__).
        Referential errors surface as `.violations`; raise IntegrityError if strict=True.
        """
        p = Path(path) if path else default_catalog_path()
        if not p.is_file():
            raise FileNotFoundError(f"Catalog not found at {p}")
        data = yaml.safe_load(p.read_text()) or {}
        if not isinstance(data, dict):
            raise ValueError(f"catalog.yaml must parse to a dict, got {type(data).__name__}")
        return cls._from_dict(data, strict=strict)

    @classmethod
    def _from_dict(cls, data: dict, *, strict: bool = False) -> Catalog:
        # Series
        series_by_name: dict[str, SeriesEntry] = {}
        for name, meta in (data.get("series") or {}).items():
            series_by_name[name] = SeriesEntry(
                name=name,
                collection=str(meta.get("collection", "")),
                description=str(meta.get("description", "")),
                skus=tuple(meta.get("skus") or []),
                lookbook_images=tuple(meta.get("lookbook_images") or []),
            )

        # Derive sku → series lookup for products that don't declare it explicitly
        sku_to_series = {sku: sname for sname, s in series_by_name.items() for sku in s.skus}

        # Products
        products_by_sku: dict[str, ProductEntry] = {}
        for i, raw in enumerate(data.get("products") or []):
            if not isinstance(raw, dict):
                raise ValueError(f"products[{i}]: expected mapping, got {type(raw).__name__}")
            sku = raw.get("sku")
            if not sku:
                raise ValueError(f"products[{i}]: missing required 'sku' field")
            products_by_sku[sku] = ProductEntry(
                sku=sku,
                name=str(raw.get("name") or ""),
                collection=str(raw.get("collection") or ""),
                price_usd=float(raw.get("price_usd") or 0.0),
                status=str(raw.get("status") or "draft"),
                branding_summary=str(raw.get("branding_summary") or ""),
                series=raw.get("series") or sku_to_series.get(sku),
                aliases=tuple(raw.get("aliases") or []),
                filename_patterns=tuple(raw.get("filename_patterns") or []),
                color_spec=dict(raw.get("color_spec") or {}),
                text_spec=tuple(raw.get("text_spec") or []),
                variants=tuple(raw.get("variants") or []),
                master=dict(raw.get("master") or {}),
                source_files=tuple(raw.get("source_files") or []),
                ai_renders=tuple(raw.get("ai_renders") or []),
                review_flags=tuple(raw.get("review_flags") or []),
                notes=str(raw.get("notes") or ""),
                limited_pieces=raw.get("limited_pieces"),
                retirement_note=raw.get("retirement_note"),
            )

        collections = dict(data.get("collections") or {})
        catalog_rules = dict(data.get("catalog_rules") or {})

        violations = cls._validate_integrity(
            collections=collections,
            catalog_rules=catalog_rules,
            series_by_name=series_by_name,
            products_by_sku=products_by_sku,
        )
        if strict and violations:
            raise IntegrityError(list(violations))

        return cls(
            version=int(data.get("version") or 0),
            generated_at=str(data.get("generated_at") or ""),
            collections=collections,
            catalog_rules=catalog_rules,
            series_by_name=series_by_name,
            products_by_sku=products_by_sku,
            unclaimed_legacy_files=dict(data.get("unclaimed_legacy_files") or {}),
            orphan_brand_files=dict(data.get("orphan_brand_files") or {}),
            violations=tuple(violations),
        )

    @staticmethod
    def _validate_integrity(
        collections: dict[str, Any],
        catalog_rules: dict[str, Any],
        series_by_name: dict[str, SeriesEntry],
        products_by_sku: dict[str, ProductEntry],
    ) -> list[Violation]:
        """Cross-reference checks. Returns violations list (empty = clean)."""
        viols: list[Violation] = []

        # 1. Every product's collection must exist in collections block
        declared_collections = set(collections.keys())
        for sku, p in products_by_sku.items():
            if p.collection not in declared_collections:
                viols.append(
                    Violation(
                        severity="referential",
                        code="unknown_collection",
                        path=f"products[{sku!r}].collection",
                        message=(
                            f"collection {p.collection!r} not declared in collections: block "
                            f"(declared: {sorted(declared_collections)})"
                        ),
                    )
                )

        # 2. Every series.skus entry must exist in products_by_sku
        for sname, s in series_by_name.items():
            for sku in s.skus:
                if sku not in products_by_sku:
                    viols.append(
                        Violation(
                            severity="referential",
                            code="series_unknown_sku",
                            path=f"series[{sname!r}].skus",
                            message=f"series references unknown SKU {sku!r}",
                        )
                    )

        # 3. Aliases must not collide: no alias should appear on more than one product,
        #    and no alias should shadow an active SKU.
        alias_owner: dict[str, str] = {}
        for sku, p in products_by_sku.items():
            for alias in p.aliases:
                if alias in products_by_sku:
                    viols.append(
                        Violation(
                            severity="referential",
                            code="alias_shadows_sku",
                            path=f"products[{sku!r}].aliases",
                            message=(
                                f"alias {alias!r} conflicts with an active SKU of the same code"
                            ),
                        )
                    )
                if alias in alias_owner and alias_owner[alias] != sku:
                    viols.append(
                        Violation(
                            severity="referential",
                            code="alias_collision",
                            path=f"products[{sku!r}].aliases",
                            message=(
                                f"alias {alias!r} also declared on products[{alias_owner[alias]!r}]"
                            ),
                        )
                    )
                alias_owner[alias] = sku

        # 4. jerseys.sku_to_patch — every mapped SKU must (a) exist in products,
        #    (b) be a member of "The Jersey Series" (brand rule: ALL jerseys live
        #    in the Jersey Series; no 'standalone jersey' concept), and
        #    (c) use a valid sport name.
        jersey_rules = (catalog_rules.get("jerseys") or {}).get("sku_to_patch") or {}
        valid_patches = {"baseball", "football", "basketball", "hockey"}
        jersey_series = series_by_name.get("The Jersey Series") or series_by_name.get(
            "Jersey Series"
        )
        jersey_skus = set(jersey_series.skus) if jersey_series else set()

        for sku, sport in jersey_rules.items():
            if sku not in products_by_sku:
                viols.append(
                    Violation(
                        severity="referential",
                        code="patch_sku_missing",
                        path=f"catalog_rules.jerseys.sku_to_patch[{sku!r}]",
                        message=f"patch mapping references unknown SKU {sku!r}",
                    )
                )
            elif sku not in jersey_skus:
                viols.append(
                    Violation(
                        severity="referential",
                        code="patch_sku_not_in_series",
                        path=f"catalog_rules.jerseys.sku_to_patch[{sku!r}]",
                        message=(
                            f"{sku!r} has a patch mapping but is not in The Jersey Series. "
                            "All jerseys must be added to the series — no standalone jerseys."
                        ),
                    )
                )
            if sport not in valid_patches:
                viols.append(
                    Violation(
                        severity="referential",
                        code="patch_sport_invalid",
                        path=f"catalog_rules.jerseys.sku_to_patch[{sku!r}]",
                        message=f"patch sport {sport!r} not in {sorted(valid_patches)}",
                    )
                )

        return viols

    # ─── Queries ────────────────────────────────────────────────────────

    def list_skus(self, active_only: bool = False) -> list[str]:
        skus = list(self.products_by_sku.keys())
        if active_only:
            skus = [s for s in skus if self.products_by_sku[s].is_active]
        return skus

    def get(self, sku: str) -> ProductEntry | None:
        return self.products_by_sku.get(sku)

    def require(self, sku: str) -> ProductEntry:
        p = self.products_by_sku.get(sku)
        if p is None:
            raise KeyError(f"SKU {sku!r} not found in catalog")
        return p

    def resolve_sku(self, sku_or_alias: str) -> ProductEntry | None:
        """Look up by current SKU or by any declared alias."""
        if sku_or_alias in self.products_by_sku:
            return self.products_by_sku[sku_or_alias]
        for p in self.products_by_sku.values():
            if sku_or_alias in p.aliases:
                return p
        return None

    def get_series(self, name: str) -> SeriesEntry | None:
        return self.series_by_name.get(name)

    def products_in_series(self, name: str) -> list[ProductEntry]:
        s = self.series_by_name.get(name)
        if not s:
            return []
        return [self.products_by_sku[sku] for sku in s.skus if sku in self.products_by_sku]

    def products_in_collection(
        self, collection: str, active_only: bool = False
    ) -> list[ProductEntry]:
        out = [p for p in self.products_by_sku.values() if p.collection == collection]
        if active_only:
            out = [p for p in out if p.is_active]
        return out

    def jersey_patch_for(self, sku: str) -> str | None:
        """Return patch sport (baseball|football|basketball|hockey) for a jersey SKU."""
        mapping = (self.catalog_rules.get("jerseys") or {}).get("sku_to_patch") or {}
        return mapping.get(sku)
