#!/usr/bin/env python3
"""Generate the per-collection designer hub: data/collections/<slug>/index.html.

Renders FROM the canonical assets/ tree via relative ../../../assets/ paths — no image
duplication (single-asset-tree lock). Reads identity.json + the generated sot.json +
copy.md. All dynamic text is HTML-escaped. DO NOT hand-edit index.html.
"""

import html
import json
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent
sys.path.insert(0, str(DATA))
import sot_common  # noqa: E402

OUT = DATA / "collections"
# index.html lives at data/collections/<slug>/ — three levels below the theme
# root, so assets/ resolves via ../../../ (was ../../, which pointed at the
# nonexistent data/assets/ and 404'd every hub image).
ASSET_PREFIX = "../../../assets/"


def e(s) -> str:
    return html.escape(str(s if s is not None else ""))


def asset(rel) -> str:
    return ASSET_PREFIX + e(rel) if rel else ""


def swatches(palette: dict) -> str:
    return "".join(
        f'<div class="sw"><span style="background:{e(hex_)}"></span>'
        f"<code>{e(name)} {e(hex_)}</code></div>"
        for name, hex_ in palette.items()
    )


def fontfaces(fonts: dict) -> str:
    """@font-face rules so the standalone hub renders the real fonts (woff2 in assets/fonts/)."""
    seen: set[str] = set()
    out = ""
    for f in fonts.values():
        fam, w = f["family"], f.get("woff2")
        if not w or fam in seen:
            continue
        seen.add(fam)
        url = "../../../" + w if w.startswith("assets/") else w
        out += (
            f"@font-face{{font-family:'{e(fam)}';"
            f"src:url('{e(url)}') format('woff2');font-display:swap;}}\n"
        )
    return out


def specimen(fonts: dict) -> str:
    rows = ""
    for role, f in fonts.items():
        fam = e(f["family"])
        rows += (
            f'<p class="spec" style="font-family:\'{fam}\'">'
            f"<small>{e(role)} — {fam}</small><br>{fam} — The Quick Brown Fox 0123</p>"
        )
    return rows


def products(sot: dict) -> str:
    cells = ""
    for p in sot.get("products", []):
        img = ""
        for col in ("image", "front_model_image"):
            r = (p.get("images", {}).get(col) or {}).get("resolved")
            if r:
                img = f'<img loading="lazy" src="{asset(r)}" alt="{e(p["name"])}">'
                break
        pre = " · PRE-ORDER" if p.get("is_preorder") else ""
        cells += (
            f"<figure>{img}<figcaption>{e(p['sku'])} — {e(p['name'])} "
            f"(${e(p.get('price'))}{pre})</figcaption></figure>"
        )
    return cells


def page(ident: dict, sot: dict, copy_md: str) -> str:
    name = e(ident["name"])
    lockup = sot.get("lockup", {})
    # Use canonical webp if present; fall back to svg_master when canonical is unresolved.
    lock_rel = lockup.get("canonical") or ((lockup.get("svg_master") or {}).get("resolved"))
    lock = asset(lock_rel)
    pal = ident["palette"]
    header = f'<img src="{lock}" alt="{name} lockup">' if lock else f"<h1>{name}</h1>"
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{name} — Collection Hub</title>
<!-- GENERATED by data/gen-collection-hub.py — DO NOT EDIT -->
<style>
{fontfaces(ident["fonts"])} body{{font-family:'Cormorant Garamond',serif;background:{e(pal["bg"])};
   color:{e(pal["text"])};margin:0 auto;padding:2rem;max-width:1100px}}
 h1,h2{{font-family:'Cinzel',serif;letter-spacing:.04em}}
 .lock img{{max-width:520px;width:100%}}
 .sw{{display:inline-flex;align-items:center;gap:.5rem;margin:.25rem 1rem .25rem 0}}
 .sw span{{width:28px;height:28px;border-radius:4px;display:inline-block;border:1px solid #666}}
 .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:1rem}}
 figure{{margin:0}} figure img{{width:100%;border-radius:6px}} figcaption{{font-size:.8rem;opacity:.8}}
 .spec{{font-size:1.6rem;margin:.4rem 0}} code{{font-family:ui-monospace,monospace;font-size:.8rem}}
</style></head><body>
<header class="lock">{header}</header>
<p><em>{e(ident["story"]["seed"])}</em></p>
<h2>Palette</h2><div>{swatches(pal)}</div>
<h2>Type</h2>{specimen(ident["fonts"])}
<h2>Products ({len(sot.get("products", []))})</h2><div class="grid">{products(sot)}</div>
<h2>Copy</h2><pre style="white-space:pre-wrap;font-family:inherit">{e(copy_md)}</pre>
</body></html>
"""


def main() -> int:
    idents = sot_common.load_identity()
    for slug, ident in idents.items():
        folder = OUT / slug
        sot = json.loads((folder / "sot.json").read_text())
        copy_md = (folder / "copy.md").read_text() if (folder / "copy.md").is_file() else ""
        (folder / "index.html").write_text(page(ident, sot, copy_md))
        print(f"{slug}/index.html generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
