"""CI gate — surface compositor-blocking SKUs in the source-photo manifest.

Reads the manifest at
``assets/products/source-photos/manifest.json`` (regenerated by
``scripts/audit_source_photos.py``) and reports every active SKU that lacks
the minimum angles (front + back) the compositor needs.

This test is INFORMATIONAL by default — it prints the blocked list as a
warning so CI logs surface it, but does NOT fail the build (per the resolved
scope decision: techflats can stand in temporarily). To promote to a hard
gate after sourcing completes, flip ``ENFORCE_MINIMUM_COVERAGE`` to True.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import pytest

from tests.sparse_guard import requires_tree

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "assets" / "products" / "source-photos" / "manifest.json"

# Every test reads the manifest under assets/ — sparse worktrees exclude that
# tree by design; full checkouts and CI still fail closed on a missing manifest.
pytestmark = requires_tree("assets/products/source-photos")

# Promote to True after every active SKU has at least front + back. Until then,
# the warning surfaces gaps without blocking the build.
ENFORCE_MINIMUM_COVERAGE = False


def test_manifest_exists():
    assert MANIFEST_PATH.exists(), (
        "assets/products/source-photos/manifest.json missing — run `python scripts/audit_source_photos.py` first."
    )


def test_manifest_schema():
    """Manifest top-level shape sanity check."""
    data = json.loads(MANIFEST_PATH.read_text())
    assert "version" in data
    assert "required_angles_by_garment_type" in data
    assert "minimum_for_compositor" in data
    assert "summary" in data
    assert "skus" in data
    assert isinstance(data["skus"], dict)
    assert len(data["skus"]) >= 30, f"expected ≥30 active SKUs in manifest, got {len(data['skus'])}"


def test_minimum_compositor_coverage():
    """Surface any SKUs missing front+back. WARN by default; FAIL if enforced."""
    data = json.loads(MANIFEST_PATH.read_text())
    blocked = [
        sku for sku, c in data["skus"].items() if not c.get("has_minimum_for_compositor", False)
    ]
    if blocked:
        msg = (
            f"{len(blocked)}/{len(data['skus'])} SKUs lack front+back source "
            f"photography (compositor-blocked): {', '.join(sorted(blocked))}"
        )
        if ENFORCE_MINIMUM_COVERAGE:
            pytest.fail(msg)
        warnings.warn(msg, UserWarning, stacklevel=1)


@pytest.mark.parametrize(
    "garment_type",
    [
        "tee",
        "hoodie",
        "crewneck",
        "jersey",
        "shorts",
        "joggers",
        "set",
        "jacket",
        "accessory",
    ],
)
def test_required_angles_defined_for_each_garment_type(garment_type):
    """Every garment type the inferrer can emit must have a required-angles list."""
    data = json.loads(MANIFEST_PATH.read_text())
    required = data["required_angles_by_garment_type"]
    assert garment_type in required, (
        f"manifest missing required_angles for garment type {garment_type!r}"
    )
    assert len(required[garment_type]) >= 2, (
        f"{garment_type}: required angles list too short ({required[garment_type]})"
    )
