#!/bin/bash
# WordPress Credentials Setup Helper
# Run this after updating .env with your actual credentials

echo "=============================================================================="
echo "🔐 WordPress Credentials Setup"
echo "=============================================================================="
echo ""
echo "📝 Step 1: Edit the .env file"
echo "   Open: /home/user/DevSkyy/.env"
echo ""
echo "   Find these lines (around line 21-22):"
echo "   WORDPRESS_CLIENT_ID=<your-actual-client-id>"
echo "   WORDPRESS_CLIENT_SECRET=<your-actual-client-secret>"
echo ""
echo "   Replace with your actual credentials:"
echo "   WORDPRESS_CLIENT_ID=12345"
echo "   WORDPRESS_CLIENT_SECRET=abcdefghijklmnop123456789"
echo ""
echo "=============================================================================="
echo "🌐 Where to Get WordPress OAuth Credentials"
echo "=============================================================================="
echo ""
echo "Option A - WordPress.com OAuth (Recommended):"
echo "   1. Visit: https://developer.wordpress.com/apps/"
echo "   2. Click 'Create New Application'"
echo "   3. Fill in:"
echo "      • Name: DevSkyy Agent Platform"
echo "      • Description: AI agent automation for WordPress"
echo "      • Website URL: http://localhost:8000"
echo "      • Redirect URLs: http://localhost:8000/api/v1/wordpress/oauth/callback"
echo "   4. Click 'Create'"
echo "   5. Copy the Client ID and Client Secret"
echo "   6. Paste into .env file"
echo ""
echo "Option B - Self-Hosted WordPress:"
echo "   1. Log into WordPress admin"
echo "   2. Go to: Users → Profile"
echo "   3. Scroll to 'Application Passwords' section"
echo "   4. Enter name: DevSkyy Agents"
echo "   5. Click 'Add New Application Password'"
echo "   6. Copy the generated password"
echo "   7. Update these in .env:"
echo "      SKYY_ROSE_SITE_URL=https://your-site.com"
echo "      SKYY_ROSE_USERNAME=your-username"
echo "      SKYY_ROSE_APP_PASSWORD=xxxx xxxx xxxx xxxx xxxx xxxx"
echo ""
echo "=============================================================================="
echo "✅ Step 2: Verify Your Configuration"
echo "=============================================================================="
echo ""
echo "After updating .env, run:"
echo "   python scripts/wordpress/quick_status.py"
echo ""
echo "You should see:"
echo "   ✅ WordPress OAuth 2.0: CONFIGURED"
echo "   ✅ WordPress Basic Auth: CONFIGURED"
echo ""
echo "=============================================================================="
echo "🚀 Step 3: Test the Integration"
echo "=============================================================================="
echo ""
echo "Once verified, you can:"
echo "   1. Start DevSkyy API: python -m uvicorn main:app --reload"
echo "   2. Submit a deployment job via /api/v1/deployment/jobs"
echo "   3. Watch the multi-agent approval workflow"
echo "   4. Track token usage and costs"
echo ""
echo "=============================================================================="
echo "📚 Need Help?"
echo "=============================================================================="
echo ""
echo "Documentation:"
echo "   • Full guide: docs/WORDPRESS_DEPLOYMENT_SETUP.md"
echo "   • Setup notes: .env.wordpress_setup"
echo "   • Examples: docs/wordpress_deployment_examples.json"
echo ""
echo "Common Issues:"
echo "   • Invalid Client ID/Secret → Check you copied correctly"
echo "   • Redirect URI mismatch → Must match exactly in WordPress.com app settings"
echo "   • Self-hosted 404 errors → Ensure WordPress 5.6+ with REST API enabled"
echo ""
echo "=============================================================================="
