// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/3d-pipeline" | "/admin/agents" | "/admin/assets" | "/admin/autonomous" | "/admin/conversion" | "/admin/elite-studio" | "/admin/elite-studio/characters" | "/admin/elite-studio/design" | "/admin/elite-studio/operations" | "/admin/elite-studio/operations/[id]" | "/admin/experience" | "/admin/huggingface" | "/admin/imagery" | "/admin/jobs" | "/admin/journey-analytics" | "/admin/mascot" | "/admin/monitoring" | "/admin/pipeline" | "/admin/qa" | "/admin/round-table" | "/admin/settings" | "/admin/social-media" | "/admin/storefront-autonomy" | "/admin/tasks" | "/admin/vercel" | "/admin/wordpress" | "/checkout" | "/collections" | "/collections/[slug]" | "/login" | "/pre-order"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/autonomy" | "/api/checkout" | "/api/conversion" | "/api/huggingface" | "/api/imagery" | "/api/jobs" | "/api/mascot" | "/api/monitoring/health" | "/api/monitoring/metrics" | "/api/pipeline-status" | "/api/pipeline/meshy" | "/api/pipeline/tripo" | "/api/products" | "/api/settings" | "/api/social-media" | "/api/social-media/analytics" | "/api/social-media/generate" | "/api/social-media/publish" | "/api/social-media/schedule" | "/api/v1/3d/generate/image" | "/api/v1/3d/generate/text" | "/api/v1/3d/jobs" | "/api/v1/3d/providers" | "/api/v1/3d/status" | "/api/wordpress/proxy" | "/api/wordpress/proxy/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/elite-studio" | "/collections"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/3d-pipeline": {}
  "/admin/agents": {}
  "/admin/assets": {}
  "/admin/autonomous": {}
  "/admin/conversion": {}
  "/admin/elite-studio": {}
  "/admin/elite-studio/characters": {}
  "/admin/elite-studio/design": {}
  "/admin/elite-studio/operations": {}
  "/admin/elite-studio/operations/[id]": { "id": string; }
  "/admin/experience": {}
  "/admin/huggingface": {}
  "/admin/imagery": {}
  "/admin/jobs": {}
  "/admin/journey-analytics": {}
  "/admin/mascot": {}
  "/admin/monitoring": {}
  "/admin/pipeline": {}
  "/admin/qa": {}
  "/admin/round-table": {}
  "/admin/settings": {}
  "/admin/social-media": {}
  "/admin/storefront-autonomy": {}
  "/admin/tasks": {}
  "/admin/vercel": {}
  "/admin/wordpress": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/autonomy": {}
  "/api/checkout": {}
  "/api/conversion": {}
  "/api/huggingface": {}
  "/api/imagery": {}
  "/api/jobs": {}
  "/api/mascot": {}
  "/api/monitoring/health": {}
  "/api/monitoring/metrics": {}
  "/api/pipeline-status": {}
  "/api/pipeline/meshy": {}
  "/api/pipeline/tripo": {}
  "/api/products": {}
  "/api/settings": {}
  "/api/social-media": {}
  "/api/social-media/analytics": {}
  "/api/social-media/generate": {}
  "/api/social-media/publish": {}
  "/api/social-media/schedule": {}
  "/api/v1/3d/generate/image": {}
  "/api/v1/3d/generate/text": {}
  "/api/v1/3d/jobs": {}
  "/api/v1/3d/providers": {}
  "/api/v1/3d/status": {}
  "/api/wordpress/proxy": {}
  "/api/wordpress/proxy/upload": {}
  "/checkout": {}
  "/collections": {}
  "/collections/[slug]": { "slug": string; }
  "/login": {}
  "/pre-order": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/elite-studio": never
  "/collections": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
