// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/3d-pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/3d-pipeline">> = Specific
  const handler = {} as typeof import("../../../app/admin/3d-pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../../app/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assets">> = Specific
  const handler = {} as typeof import("../../../app/admin/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/autonomous/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/autonomous">> = Specific
  const handler = {} as typeof import("../../../app/admin/autonomous/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/conversion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/conversion">> = Specific
  const handler = {} as typeof import("../../../app/admin/conversion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/elite-studio/characters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/elite-studio/characters">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/characters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/elite-studio/design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/elite-studio/design">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/elite-studio/operations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/elite-studio/operations/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/operations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/elite-studio/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/elite-studio/operations">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/elite-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/elite-studio">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/experience/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/experience">> = Specific
  const handler = {} as typeof import("../../../app/admin/experience/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/huggingface/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/huggingface">> = Specific
  const handler = {} as typeof import("../../../app/admin/huggingface/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/imagery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/imagery">> = Specific
  const handler = {} as typeof import("../../../app/admin/imagery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../../app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/journey-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journey-analytics">> = Specific
  const handler = {} as typeof import("../../../app/admin/journey-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/mascot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mascot">> = Specific
  const handler = {} as typeof import("../../../app/admin/mascot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring">> = Specific
  const handler = {} as typeof import("../../../app/admin/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/admin/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qa">> = Specific
  const handler = {} as typeof import("../../../app/admin/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/round-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/round-table">> = Specific
  const handler = {} as typeof import("../../../app/admin/round-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/social-media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social-media">> = Specific
  const handler = {} as typeof import("../../../app/admin/social-media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/storefront-autonomy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/storefront-autonomy">> = Specific
  const handler = {} as typeof import("../../../app/admin/storefront-autonomy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tasks">> = Specific
  const handler = {} as typeof import("../../../app/admin/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/vercel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vercel">> = Specific
  const handler = {} as typeof import("../../../app/admin/vercel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/wordpress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/wordpress">> = Specific
  const handler = {} as typeof import("../../../app/admin/wordpress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/collections/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/collections/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../../app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pre-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pre-order">> = Specific
  const handler = {} as typeof import("../../../app/pre-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/autonomy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/autonomy">> = Specific
  const handler = {} as typeof import("../../../app/api/autonomy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/conversion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversion">> = Specific
  const handler = {} as typeof import("../../../app/api/conversion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/huggingface/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/huggingface">> = Specific
  const handler = {} as typeof import("../../../app/api/huggingface/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/imagery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imagery">> = Specific
  const handler = {} as typeof import("../../../app/api/imagery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../../app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mascot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mascot">> = Specific
  const handler = {} as typeof import("../../../app/api/mascot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/health">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline-status">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline/meshy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/meshy">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline/meshy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline/tripo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/tripo">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline/tripo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/social-media/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-media/analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/social-media/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/social-media/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-media/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/social-media/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/social-media/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-media/publish">> = Specific
  const handler = {} as typeof import("../../../app/api/social-media/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/social-media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-media">> = Specific
  const handler = {} as typeof import("../../../app/api/social-media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/social-media/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-media/schedule">> = Specific
  const handler = {} as typeof import("../../../app/api/social-media/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/3d/generate/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/3d/generate/image">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/3d/generate/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/3d/generate/text/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/3d/generate/text">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/3d/generate/text/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/3d/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/3d/jobs">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/3d/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/3d/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/3d/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/3d/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/3d/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/3d/status">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/3d/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wordpress/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wordpress/proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/wordpress/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wordpress/proxy/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wordpress/proxy/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/wordpress/proxy/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/elite-studio/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/elite-studio">> = Specific
  const handler = {} as typeof import("../../../app/admin/elite-studio/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/collections/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../../app/collections/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
