"""Seed the DevSkyy database with SkyyRose product catalog.

Mirrors the 28 products from wordpress-theme/skyyrose-flagship/inc/product-catalog.php.

Usage:
    python -m database.seed_catalog
"""

from __future__ import annotations

import asyncio
import json
import uuid

PRODUCTS = [
    # ─── BLACK ROSE COLLECTION ───────────────────────────────────────
    {
        "sku": "br-001",
        "name": "BLACK Rose Crewneck",
        "price": 35.00,
        "collection": "black-rose",
        "category": "Crewnecks",
        "description": "Gothic luxury blooms in twilight. Embroidered with defiant elegance, a dark romance woven in every thread.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-002",
        "name": "BLACK Rose Joggers",
        "price": 50.00,
        "collection": "black-rose",
        "category": "Joggers",
        "description": "Twilight comfort meets gothic romance. Embroidered black roses bloom on soft fabric.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-003",
        "name": "BLACK is Beautiful Jersey",
        "price": 45.00,
        "collection": "black-rose",
        "category": "Jerseys",
        "description": "A bold statement in luxury athletic wear. Black is beautiful, and this jersey proves it.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-004",
        "name": "BLACK Rose Hoodie",
        "price": 40.00,
        "collection": "black-rose",
        "category": "Hoodies",
        "description": "Gothic luxury in twilight shadows. Intricate embroidery captures the bloom of darkness.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-005",
        "name": "BLACK Rose Hoodie — Signature Edition",
        "price": 65.00,
        "collection": "black-rose",
        "category": "Hoodies",
        "description": "The definitive Black Rose hoodie. Signature edition with premium detailing and numbered tag.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-006",
        "name": "BLACK Rose Sherpa Jacket",
        "price": 95.00,
        "collection": "black-rose",
        "category": "Jackets",
        "description": "Lustrous black satin with plush Sherpa lining, crowned by an exquisite embroidered rose.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-007",
        "name": "BLACK Rose x Love Hurts Basketball Shorts",
        "price": 65.00,
        "collection": "black-rose",
        "category": "Shorts",
        "description": "Two worlds collide. A cross-collection collaboration merging Black Rose darkness with Love Hurts fire.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "br-008",
        "name": "Women's BLACK Rose Hooded Dress",
        "price": 120.00,
        "collection": "black-rose",
        "category": "Dresses",
        "description": "Intricate black rose embroidery and a silhouette of gothic mystery. Designed for the fearless.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["XS", "S", "M", "L", "XL", "2XL"],
        "color": "Black",
    },
    {
        "sku": "br-d01",
        "name": "BLACK is Beautiful Hockey Jersey (Teal)",
        "price": 55.00,
        "collection": "black-rose",
        "category": "Jerseys",
        "description": "Hooded hockey jersey in bold black and teal. Streetwear meets the rink.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black/Teal",
    },
    {
        "sku": "br-d02",
        "name": "BLACK is Beautiful Football Jersey (Red #80)",
        "price": 55.00,
        "collection": "black-rose",
        "category": "Jerseys",
        "description": "Red football jersey with #80 numbering. Game-day luxury meets street culture.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Red",
    },
    {
        "sku": "br-d03",
        "name": "BLACK is Beautiful Football Jersey (White #32)",
        "price": 55.00,
        "collection": "black-rose",
        "category": "Jerseys",
        "description": "White football jersey with #32. Clean luxury on the gridiron.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "White",
    },
    {
        "sku": "br-d04",
        "name": "BLACK is Beautiful Basketball Jersey",
        "price": 45.00,
        "collection": "black-rose",
        "category": "Jerseys",
        "description": 'Basketball jersey with "The Bay" branding. Court-ready luxury streetwear.',
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black/Red",
    },
    # ─── LOVE HURTS COLLECTION ───────────────────────────────────────
    {
        "sku": "lh-001",
        "name": "The Fannie Pack",
        "price": 65.00,
        "collection": "love-hurts",
        "category": "Accessories",
        "description": "Luxury fanny pack embodying Oakland grit, passion, and the defiant bloom of a street rose.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["One Size"],
        "color": "Black",
    },
    {
        "sku": "lh-002",
        "name": "Love Hurts Joggers",
        "price": 95.00,
        "collection": "love-hurts",
        "category": "Joggers",
        "description": "Oakland grit meets luxury. Feel the fire with the embroidered rose, a symbol of passion.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "lh-003",
        "name": "Love Hurts Basketball Shorts",
        "price": 75.00,
        "collection": "love-hurts",
        "category": "Shorts",
        "description": "Oakland-inspired luxury streetwear. Defiant rose design on breathable mesh.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "lh-004",
        "name": "Love Hurts Varsity Jacket",
        "price": 265.00,
        "collection": "love-hurts",
        "category": "Jackets",
        "description": "Oakland street couture. Satin, bold fire-red script, hidden rose garden in hood.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black",
    },
    {
        "sku": "lh-005",
        "name": "Love Hurts Windbreaker",
        "price": 145.00,
        "collection": "love-hurts",
        "category": "Jackets",
        "description": "Oakland fire meets the elements. Blush pink windbreaker with Love Hurts text and rose detailing.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Blush",
    },
    # ─── SIGNATURE COLLECTION ────────────────────────────────────────
    {
        "sku": "sg-001",
        "name": "The Bay Set",
        "price": 195.00,
        "collection": "signature",
        "category": "Sets",
        "description": "Embody West Coast luxury with this exclusive ensemble. Iconic blue rose and vibrant Bay Area skyline.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Blue",
    },
    {
        "sku": "sg-002",
        "name": "Stay Golden Set",
        "price": 65.00,
        "collection": "signature",
        "category": "Sets",
        "description": "Embrace West Coast prestige. Luxurious statement of Bay Area style featuring signature rose.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["XS", "S", "M", "L", "XL", "2XL"],
        "color": "Gold",
    },
    {
        "sku": "sg-003",
        "name": "The Signature Tee (Orchid)",
        "price": 15.00,
        "collection": "signature",
        "category": "Tees",
        "description": "The essential SkyyRose tee in a rich orchid colorway. Soft cotton with embroidered rose.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Orchid",
    },
    {
        "sku": "sg-004",
        "name": "Signature Tee (White)",
        "price": 15.00,
        "collection": "signature",
        "category": "Tees",
        "description": "The essential SkyyRose tee in clean white. Minimal design with signature branding.",
        "quantity": 250,
        "is_active": False,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "White",
    },
    {
        "sku": "sg-005",
        "name": "Stay Golden Tee",
        "price": 40.00,
        "collection": "signature",
        "category": "Tees",
        "description": "The classic Stay Golden silhouette. Timeless Bay Area luxury in every stitch.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["XS", "S", "M", "L", "XL", "2XL"],
        "color": "Gold",
    },
    {
        "sku": "sg-006",
        "name": "Mint & Lavender Hoodie",
        "price": 45.00,
        "collection": "signature",
        "category": "Hoodies",
        "description": "Sweet pastel vibes meet streetwear luxury. Mint and lavender colorblock with signature rose detail.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Mint/Lavender",
    },
    {
        "sku": "sg-007",
        "name": "The Signature Beanie (Black)",
        "price": 25.00,
        "collection": "signature",
        "category": "Accessories",
        "description": "Classic cuffed beanie in black with woven SkyyRose rose patch.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["One Size"],
        "color": "Black",
    },
    {
        "sku": "sg-008",
        "name": "The Signature Beanie (Forest Green)",
        "price": 25.00,
        "collection": "signature",
        "category": "Accessories",
        "description": "Classic cuffed beanie in forest green with woven SkyyRose rose patch in teal accent.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["One Size"],
        "color": "Forest Green",
    },
    {
        "sku": "sg-009",
        "name": "The Sherpa Jacket",
        "price": 80.00,
        "collection": "signature",
        "category": "Jackets",
        "description": "Plush sherpa warmth in the SkyyRose signature colorway. Luxury outerwear for the West Coast.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Cream",
    },
    {
        "sku": "sg-010",
        "name": "The Bridge Series Shorts",
        "price": 25.00,
        "collection": "signature",
        "category": "Shorts",
        "description": "From the Bridge Series. Athletic shorts celebrating the iconic Bay Area bridges.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL"],
        "color": "Navy",
    },
    {
        "sku": "sg-011",
        "name": "Original Label Tee (White)",
        "price": 30.00,
        "collection": "signature",
        "category": "Tees",
        "description": "The original SkyyRose label tee in clean white. Minimal design with signature branding.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "White",
    },
    {
        "sku": "sg-012",
        "name": "Original Label Tee (Orchid)",
        "price": 30.00,
        "collection": "signature",
        "category": "Tees",
        "description": "The original SkyyRose label tee in rich orchid. Minimal design with signature branding.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Orchid",
    },
    {
        "sku": "sg-d01",
        "name": "The Multi-Colored Windbreaker Set",
        "price": 75.00,
        "collection": "signature",
        "category": "Sets",
        "description": "Pastel V-chevron windbreaker set — hooded zip jacket and matching jogger pants.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "White/Pastel Multi",
    },
    {
        "sku": "sg-d02",
        "name": "The SkyyRose Collection Shorts",
        "price": 45.00,
        "collection": "signature",
        "category": "Shorts",
        "description": 'Black athletic shorts with gold accents and "The SkyyRose Collection" script branding.',
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Black/Gold",
    },
    {
        "sku": "sg-d03",
        "name": "Mint Rose Crewneck + Jogger Set",
        "price": 75.00,
        "collection": "signature",
        "category": "Sets",
        "description": "Mint green crewneck and matching joggers with purple rose-growing-from-concrete graphic.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "color": "Mint Green/Purple",
    },
    {
        "sku": "sg-d04",
        "name": "Mint Rose Hooded Dress",
        "price": 65.00,
        "collection": "signature",
        "category": "Dresses",
        "description": "Mint green hooded dress with large purple rose-growing-from-concrete graphic. Kangaroo pocket, relaxed fit.",
        "quantity": 250,
        "is_active": True,
        "sizes": ["XS", "S", "M", "L", "XL", "2XL"],
        "color": "Mint Green/Purple",
    },
]


async def seed():
    """Seed all 28 SkyyRose products into the database."""
    from database.db import Product, db_manager

    await db_manager.initialize()

    async with db_manager.session() as session:
        # Check if products already exist
        from sqlalchemy import func, select

        count_result = await session.execute(select(func.count()).select_from(Product))
        existing = count_result.scalar() or 0

        if existing > 0:
            print(f"Database already has {existing} products. Skipping seed.")
            print("To re-seed, delete devskyy.db and run again.")
            return

        for p in PRODUCTS:
            product = Product(
                id=str(uuid.uuid4()),
                sku=p["sku"],
                name=p["name"],
                description=p["description"],
                price=p["price"],
                quantity=p["quantity"],
                category=p["category"],
                collection=p["collection"],
                is_active=p["is_active"],
                variants_json=json.dumps({"sizes": p["sizes"], "color": p["color"]}),
            )
            session.add(product)

        await session.commit()

    print(f"Seeded {len(PRODUCTS)} products:")
    collections = {}
    for p in PRODUCTS:
        c = p["collection"]
        collections[c] = collections.get(c, 0) + 1
    for c, n in collections.items():
        print(f"  {c}: {n} products")


if __name__ == "__main__":
    asyncio.run(seed())
