<?php
/**
 * SkyyRose Brand Constants — AUTO-GENERATED.
 *
 * Source of truth: assets/brand/brand.yaml
 * Generator:       scripts/sync_brand_to_php.py
 * Generated:       2026-04-29T10:38:24Z
 *
 * DO NOT EDIT THIS FILE. Edit brand.yaml and re-run the generator.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

// ─── Tagline ────────────────────────────────────────────────────────
define( 'SKYYROSE_BRAND_TAGLINE', 'Luxury Grows from Concrete.' );
define( 'SKYYROSE_RETIRED_TAGLINES', ['Where Love Meets Luxury'] );

// ─── Brand identity ─────────────────────────────────────────────────
define( 'SKYYROSE_BRAND_NAME', 'SkyyRose' );
define( 'SKYYROSE_LEGAL_NAME', 'The Skyy Rose Collection LLC' );
define( 'SKYYROSE_BRAND_FOUNDER', 'Corey Foster' );
define( 'SKYYROSE_BRAND_ORIGIN', 'Oakland, CA' );
define( 'SKYYROSE_BRAND_MISSION', 'Luxury streetwear born from concrete. SkyyRose brings Oakland\'s grit
into premium fashion — gothic romance, passionate emotion, and Bay Area
essentials woven into every piece.' );

// ─── Color palette ──────────────────────────────────────────────────
if ( ! defined( 'SKYYROSE_COLOR_DARK' ) ) define( 'SKYYROSE_COLOR_DARK', '#0A0A0A' );
if ( ! defined( 'SKYYROSE_COLOR_ROSE_GOLD' ) ) define( 'SKYYROSE_COLOR_ROSE_GOLD', '#B76E79' );
if ( ! defined( 'SKYYROSE_COLOR_GOLD' ) ) define( 'SKYYROSE_COLOR_GOLD', '#D4AF37' );
if ( ! defined( 'SKYYROSE_COLOR_CRIMSON' ) ) define( 'SKYYROSE_COLOR_CRIMSON', '#DC143C' );
if ( ! defined( 'SKYYROSE_COLOR_SILVER' ) ) define( 'SKYYROSE_COLOR_SILVER', '#C0C0C0' );

// ─── URLs ───────────────────────────────────────────────────────────
define( 'SKYYROSE_URL_FLAGSHIP', 'https://skyyrose.co' );
define( 'SKYYROSE_URL_DASHBOARD', 'https://devskyy.app' );

// ─── Collections ────────────────────────────────────────────────────
if ( ! function_exists( 'skyyrose_brand_collections' ) ) {
    function skyyrose_brand_collections() {
        return [
            'black-rose' => [
                'display_name'    => 'BLACK ROSE',
                'tagline'         => 'Luxury Grows from Concrete.',
                'description'     => 'Gothic luxury — Oakland grit meets dark elegance. The brand\'s flagship collection: where streetwear toughness meets premium craftsmanship.',
                'theme'           => 'gothic romance meets Oakland street luxury',
                'mood'            => 'dark, powerful, mysterious, luxurious',
                'inspiration'     => 'Gothic romance, Bay Area night life, street art',
                'hero_scene'      => 'Bay Bridge at night, street luxury',
                'target_audience' => 'Oakland / Bay Area streetwear enthusiasts, gothic luxury',
                'palette'         => [
                    'primary' => '#0A0A0A',
                    'secondary' => '#1A0A0A',
                    'accent' => '#B76E79',
                    'highlight' => '#C0C0C0',
                    'text' => '#F5F5F5',
                ],
            ],
            'love-hurts' => [
                'display_name'    => 'LOVE HURTS',
                'tagline'         => 'Wear your heart outside.',
                'description'     => 'Feel the fire. Love Hurts channels raw emotion and Bay Area passion into pieces that wear your heart on your sleeve — literally.',
                'theme'           => 'Beauty and the Beast, enchanted rose, passionate emotion',
                'mood'            => 'passionate, emotional, bold, raw',
                'inspiration'     => 'Beauty and the Beast, enchanted rose, Oakland resilience',
                'hero_scene'      => 'Enchanted rose dome, gothic cathedral atmosphere',
                'target_audience' => 'Oakland streetwear, passionate fashion lovers',
                'palette'         => [
                    'primary' => '#1A0A0A',
                    'secondary' => '#DC143C',
                    'accent' => '#B76E79',
                    'highlight' => '#8B0000',
                    'text' => '#F5F5F5',
                ],
            ],
            'signature' => [
                'display_name'    => 'SIGNATURE',
                'tagline'         => 'Rose gold runway.',
                'description'     => 'The crown jewel. Timeless essentials in rose gold, inspired by San Francisco\'s Golden Gate and the city\'s fashion-forward spirit.',
                'theme'           => 'Bay Area / Golden Gate / fashion runway',
                'mood'            => 'elegant, golden, refined, iconic',
                'inspiration'     => 'San Francisco Golden Gate, golden hour, Bay Area fashion',
                'hero_scene'      => 'Golden Gate Bridge at golden hour, fashion runway through fog',
                'target_audience' => 'fashion-forward, San Francisco premium shoppers',
                'palette'         => [
                    'primary' => '#1A1205',
                    'secondary' => '#D4AF37',
                    'accent' => '#B76E79',
                    'highlight' => '#F5DEB3',
                    'text' => '#F5F5F5',
                ],
            ],
            'kids' => [
                'display_name'    => 'KIDS CAPSULE',
                'tagline'         => 'Playful luxury, junior fits.',
                'description'     => 'Junior SkyyRose. Coordinated sets with the same craftsmanship as adult collections, sized and styled for kids.',
                'theme'           => 'playful luxury for junior SkyyRose fans',
                'mood'            => 'playful, bright, premium',
                'inspiration'     => 'SkyyRose junior collection, coordinated sets',
                'hero_scene'      => 'bright playroom / outdoor play scene',
                'target_audience' => 'parents buying premium junior streetwear',
                'palette'         => [
                    'primary' => '#0A0A0A',
                    'secondary' => '#B76E79',
                    'accent' => '#D4AF37',
                    'highlight' => '#F5F5F5',
                    'text' => '#1A1A1A',
                ],
            ],
        ];
    }
}

// ─── Social handles ─────────────────────────────────────────────────
if ( ! function_exists( 'skyyrose_social_handles' ) ) {
    function skyyrose_social_handles() {
        return [
            'instagram' => '@skyyroseco',
            'twitter' => '@skyyroseco',
            'tiktok' => '@skyyroseco',
            'youtube' => '@skyyroseco',
            'email' => 'skyyroseco@gmail.com',
        ];
    }
}

// ─── JSON-LD Organization schema (for SEO) ──────────────────────────
if ( ! function_exists( 'skyyrose_json_ld_organization' ) ) {
    function skyyrose_json_ld_organization() {
        return [
            '@context'    => 'https://schema.org',
            '@type'       => 'Organization',
            'name'        => SKYYROSE_BRAND_NAME,
            'legalName'   => SKYYROSE_LEGAL_NAME,
            'founder'     => SKYYROSE_BRAND_FOUNDER,
            'slogan'      => SKYYROSE_BRAND_TAGLINE,
            'url'         => SKYYROSE_URL_FLAGSHIP,
            'sameAs'      => array_values( array_filter( skyyrose_social_handles() ) ),
        ];
    }
}

// End of auto-generated file.
