<?php
/**
 * Collection SOT Reader
 *
 * Reads per-collection sot.json (the generated Single Source of Truth) and
 * exposes three helper accessors for the visual surfaces that templates need:
 * scene portrait, hero backdrop, and collection lockup.
 *
 * The sot.json files live at:
 *   data/collections/<slug>/sot.json
 * and are generated by data/build-collection-sot.py — do not hand-edit them.
 *
 * All returned values are theme-relative URIs ready to be passed to esc_url()
 * and prefixed with SKYYROSE_ASSETS_URI in the calling template, matching the
 * same convention used for $c['hero_bg'] and $c['hero_logo'] in page.php.
 *
 * Resolved paths in sot.json are relative to the theme's assets/ directory
 * (e.g. "branding/hero/forbidden-midnight-1280w.webp"). The helpers prepend
 * a leading "/" so callers can safely concatenate: SKYYROSE_ASSETS_URI . $uri.
 *
 * Hard-fail-soft: every function returns '' when a key or file is absent —
 * no fatals, no warnings. Callers fall back to hand-maintained values when ''.
 *
 * Accessors (all return string — '' on miss):
 *   skyyrose_sot_scene($slug)  → imagery.scene_portrait.resolved
 *   skyyrose_sot_hero($slug)   → imagery.hero_backdrop.resolved
 *   skyyrose_sot_lockup($slug) → lockup.display_webp.resolved
 *                                  then lockup.source_art.resolved (fallback)
 *                                  then lockup.canonical (string fallback)
 *
 * @package SkyyRose
 * @since   1.6.3
 */

defined( 'ABSPATH' ) || exit;

/**
 * Read and cache a collection's sot.json as an associative array.
 *
 * Uses the WordPress object cache (wp_cache_get/set) so the JSON file is
 * decoded at most once per request per slug.
 *
 * @param  string $slug Collection slug: black-rose, love-hurts, signature, kids-capsule.
 * @return array<string,mixed> Decoded sot.json data, or empty array on failure.
 */
function skyyrose_get_collection_sot( $slug ) {
	$slug = sanitize_key( $slug );
	if ( '' === $slug ) {
		return array();
	}

	$cache_key   = 'skyyrose_sot_' . $slug;
	$cache_group = 'skyyrose_sot';

	$cached = wp_cache_get( $cache_key, $cache_group );
	if ( false !== $cached ) {
		// wp_cache_get returns false on miss; anything else (including an empty
		// array we stored) is a valid hit.
		return $cached;
	}

	// Build the absolute path inside the theme directory.
	// ABSPATH guard: SKYYROSE_DIR resolves to an absolute server path; the
	// slug has been sanitize_key'd to [a-z0-9_-] — no directory traversal possible.
	$sot_file = SKYYROSE_DIR . '/data/collections/' . $slug . '/sot.json';

	if ( ! file_exists( $sot_file ) ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$raw = file_get_contents( $sot_file );
	if ( false === $raw ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	$data = json_decode( $raw, true );
	if ( ! is_array( $data ) ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	wp_cache_set( $cache_key, $data, $cache_group );
	return $data;
}

/**
 * Extract a "resolved" image path from a sot.json imagery slot.
 *
 * sot.json imagery values are either null or an object with a "resolved" key
 * containing a path relative to the theme's assets/ directory, e.g.:
 *   "images/homepage-col-black-rose.webp"
 *
 * Returns a string with a leading "/" so callers can directly concatenate
 * with SKYYROSE_ASSETS_URI:
 *   esc_url( SKYYROSE_ASSETS_URI . skyyrose_sot_hero( $slug ) )
 *
 * @param  string $slug     Collection slug.
 * @param  string $section  Top-level sot.json key: 'imagery' or 'lockup'.
 * @param  string $key      Key within that section, e.g. 'hero_backdrop'.
 * @param  string $subkey   Key within that slot, e.g. 'resolved'.
 * @return string Theme-relative URI with leading '/', or '' on miss.
 */
function skyyrose_sot_resolve_path( $slug, $section, $key, $subkey = 'resolved' ) {
	$sot = skyyrose_get_collection_sot( $slug );
	if ( empty( $sot ) ) {
		return '';
	}

	if ( ! isset( $sot[ $section ] ) || ! is_array( $sot[ $section ] ) ) {
		return '';
	}

	$slot = $sot[ $section ][ $key ] ?? null;

	// The slot can be null (absent imagery) or an object (array after json_decode).
	if ( ! is_array( $slot ) ) {
		return '';
	}

	$resolved = $slot[ $subkey ] ?? '';
	if ( ! is_string( $resolved ) || '' === $resolved ) {
		return '';
	}

	// Normalise: strip any accidental leading slash before re-adding one, so
	// the return value is always "/<path>" regardless of what the generator emits.
	return '/' . ltrim( $resolved, '/' );
}

/**
 * Get the scene portrait URI for a collection from its sot.json.
 *
 * Maps to: imagery.scene_portrait.resolved
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_scene( $slug )
 *
 * Scene portrait is a collection world-art image used on collection
 * cards, panels, and portals (e.g. homepage collection rings).
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_scene( $slug ) {
	return skyyrose_sot_resolve_path( $slug, 'imagery', 'scene_portrait' );
}

/**
 * Get the hero backdrop URI for a collection from its sot.json.
 *
 * Maps to: imagery.hero_backdrop.resolved
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_hero( $slug )
 *
 * Hero backdrop is the full-bleed background image behind the collection
 * hero section. Corresponds to $c['hero_bg'] in collection-content.php.
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_hero( $slug ) {
	return skyyrose_sot_resolve_path( $slug, 'imagery', 'hero_backdrop' );
}

/**
 * Get the collection lockup (display logo) URI from sot.json.
 *
 * Priority:
 *   1. lockup.display_webp.resolved  — canonical display WebP (preferred)
 *   2. lockup.source_art.resolved    — source art (fallback when display_webp absent)
 *   3. lockup.canonical              — raw string path (last resort)
 *
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_lockup( $slug )
 *
 * Corresponds to $c['hero_logo'] in collection-content.php.
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_lockup( $slug ) {
	// Priority 1: display_webp.resolved.
	$uri = skyyrose_sot_resolve_path( $slug, 'lockup', 'display_webp' );
	if ( '' !== $uri ) {
		return $uri;
	}

	// Priority 2: source_art.resolved.
	$uri = skyyrose_sot_resolve_path( $slug, 'lockup', 'source_art' );
	if ( '' !== $uri ) {
		return $uri;
	}

	// Priority 3: lockup.canonical (plain string, not a slot object).
	$sot = skyyrose_get_collection_sot( $slug );
	if ( empty( $sot ) ) {
		return '';
	}
	$canonical = $sot['lockup']['canonical'] ?? '';
	if ( is_string( $canonical ) && '' !== $canonical ) {
		return '/' . ltrim( $canonical, '/' );
	}

	return '';
}
