<?php
/**
 * Collection SOT Reader
 *
 * Reads per-collection sot.json (the generated Single Source of Truth) and
 * exposes three helper accessors for the visual surfaces that templates need:
 * scene portrait, hero backdrop, and collection lockup.
 *
 * The sot.json files live at:
 *   data/collections/<slug>/sot.json
 * and are generated by data/build-collection-sot.py — do not hand-edit them.
 *
 * All returned values are theme-relative URIs ready to be passed to esc_url()
 * and prefixed with SKYYROSE_ASSETS_URI in the calling template, matching the
 * same convention used for $c['hero_bg'] and $c['hero_logo'] in page.php.
 *
 * Resolved paths in sot.json are relative to the theme's assets/ directory
 * (e.g. "branding/hero/forbidden-midnight-1280w.webp"). The helpers prepend
 * a leading "/" so callers can safely concatenate: SKYYROSE_ASSETS_URI . $uri.
 *
 * Hard-fail-soft: every function returns '' when a key or file is absent —
 * no fatals, no warnings. Callers fall back to hand-maintained values when ''.
 *
 * Accessors (all return string — '' on miss):
 *   skyyrose_sot_scene($slug)  → imagery.scene_portrait.resolved
 *   skyyrose_sot_hero($slug)   → imagery.hero_backdrop.resolved
 *   skyyrose_sot_lockup($slug) → lockup.display_webp.resolved
 *                                  then lockup.source_art.resolved (fallback)
 *                                  then lockup.canonical (string fallback)
 *
 * @package SkyyRose
 * @since   1.6.3
 */

defined( 'ABSPATH' ) || exit;

/**
 * Read and cache a collection's sot.json as an associative array.
 *
 * Uses the WordPress object cache (wp_cache_get/set) so the JSON file is
 * decoded at most once per request per slug.
 *
 * @param  string $slug Collection slug: black-rose, love-hurts, signature, kids-capsule.
 * @return array<string,mixed> Decoded sot.json data, or empty array on failure.
 */
function skyyrose_get_collection_sot( $slug ) {
	$slug = sanitize_key( $slug );
	if ( '' === $slug ) {
		return array();
	}

	$cache_key   = 'skyyrose_sot_' . $slug;
	$cache_group = 'skyyrose_sot';

	$cached = wp_cache_get( $cache_key, $cache_group );
	if ( false !== $cached ) {
		// wp_cache_get returns false on miss; anything else (including an empty
		// array we stored) is a valid hit.
		return $cached;
	}

	// Build the absolute path inside the theme directory.
	// ABSPATH guard: SKYYROSE_DIR resolves to an absolute server path; the
	// slug has been sanitize_key'd to [a-z0-9_-] — no directory traversal possible.
	$sot_file = SKYYROSE_DIR . '/data/collections/' . $slug . '/sot.json';

	if ( ! file_exists( $sot_file ) ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$raw = file_get_contents( $sot_file );
	if ( false === $raw ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	$data = json_decode( $raw, true );
	if ( ! is_array( $data ) ) {
		wp_cache_set( $cache_key, array(), $cache_group );
		return array();
	}

	wp_cache_set( $cache_key, $data, $cache_group );
	return $data;
}

/**
 * Extract a "resolved" image path from a sot.json imagery slot.
 *
 * Imagery slot values are either null or an object with a "resolved" key
 * containing a path relative to the theme's assets/ directory, e.g.:
 *   "images/homepage-col-black-rose.webp"
 *
 * Returns a string with a leading "/" so callers can directly concatenate
 * with SKYYROSE_ASSETS_URI:
 *   esc_url( SKYYROSE_ASSETS_URI . skyyrose_sot_hero( $slug ) )
 *
 * @param  string $slug     Collection slug.
 * @param  string $section  Top-level sot.json key: 'imagery' or 'lockup'.
 * @param  string $key      Key within that section, e.g. 'hero_backdrop'.
 * @param  string $subkey   Key within that slot, e.g. 'resolved'.
 * @return string Theme-relative URI with leading '/', or '' on miss.
 */
function skyyrose_sot_resolve_path( $slug, $section, $key, $subkey = 'resolved' ) {
	$sot = skyyrose_get_collection_sot( $slug );
	if ( empty( $sot ) ) {
		return '';
	}

	if ( ! isset( $sot[ $section ] ) || ! is_array( $sot[ $section ] ) ) {
		return '';
	}

	$slot = $sot[ $section ][ $key ] ?? null;

	// The slot can be null (absent imagery) or an object (array after json_decode).
	if ( ! is_array( $slot ) ) {
		return '';
	}

	$resolved = $slot[ $subkey ] ?? '';
	if ( ! is_string( $resolved ) || '' === $resolved ) {
		return '';
	}

	// Normalise: strip any accidental leading slash before re-adding one, so
	// the return value is always "/<path>" regardless of what the generator emits.
	return '/' . ltrim( $resolved, '/' );
}

/**
 * Get the scene portrait URI for a collection from its sot.json.
 *
 * Maps to: imagery.scene_portrait.resolved
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_scene( $slug )
 *
 * Scene portrait is a collection world-art image used on collection
 * cards, panels, and portals (e.g. homepage collection rings).
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_scene( $slug ) {
	return skyyrose_sot_resolve_path( $slug, 'imagery', 'scene_portrait' );
}

/**
 * Get the hero backdrop URI for a collection from its sot.json.
 *
 * Maps to: imagery.hero_backdrop.resolved
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_hero( $slug )
 *
 * Hero backdrop is the full-bleed background image behind the collection
 * hero section. Corresponds to $c['hero_bg'] in collection-content.php.
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_hero( $slug ) {
	return skyyrose_sot_resolve_path( $slug, 'imagery', 'hero_backdrop' );
}

/**
 * Get the collection lockup (display logo) URI from sot.json.
 *
 * Priority:
 *   1. lockup.display_webp.resolved  — canonical display WebP (preferred)
 *   2. lockup.source_art.resolved    — source art (fallback when display_webp absent)
 *   3. lockup.canonical              — raw string path (last resort)
 *
 * Usage: SKYYROSE_ASSETS_URI . skyyrose_sot_lockup( $slug )
 *
 * Corresponds to $c['hero_logo'] in collection-content.php.
 *
 * @param  string $slug Collection slug.
 * @return string Theme-relative URI (leading '/'), or '' when absent.
 */
function skyyrose_sot_lockup( $slug ) {
	// Priority 1: display_webp.resolved.
	$uri = skyyrose_sot_resolve_path( $slug, 'lockup', 'display_webp' );
	if ( '' !== $uri ) {
		return $uri;
	}

	// Priority 2: source_art.resolved.
	$uri = skyyrose_sot_resolve_path( $slug, 'lockup', 'source_art' );
	if ( '' !== $uri ) {
		return $uri;
	}

	// Priority 3: lockup.canonical (plain string, not a slot object).
	$sot = skyyrose_get_collection_sot( $slug );
	if ( empty( $sot ) ) {
		return '';
	}
	$canonical = $sot['lockup']['canonical'] ?? '';
	if ( is_string( $canonical ) && '' !== $canonical ) {
		return '/' . ltrim( $canonical, '/' );
	}

	return '';
}

/**
 * Resolve a per-SKU PRODUCT image through the SOT, front-first.
 *
 * This is the runtime bridge that closes the documented gap (templates used to
 * hardcode `/images/products/...` paths instead of consulting the SOT). Every
 * surface that shows a product image — editorial tiles, style cards, landing
 * pages — must resolve it through here so the imagery follows the catalog/SOT
 * and can never silently drift to a stale or wrong asset.
 *
 * Resolution order:
 *   1. The deployed collection sot.json (data/collections/<slug>/sot.json) —
 *      products[].images.<slot>.resolved, walked front-first per the SOT
 *      `_authority` (on-model render before flat packshot).
 *   2. The catalog CSV columns via skyyrose_get_product() (also theme-local).
 *   3. '' — caller / the _uri wrapper substitutes a placeholder.
 *
 * View → ordered image-slot chain:
 *   'front'    → front_model_image, image
 *   'back'     → back_model_image, back_image
 *   'packshot' → image, front_model_image
 *
 * Returns a theme-relative URI with a leading '/' (assets-relative, matching
 * skyyrose_sot_hero/scene/lockup), so callers concatenate:
 *   esc_url( SKYYROSE_ASSETS_URI . skyyrose_sot_product_image( $sku, $view ) )
 * or use skyyrose_sot_product_image_uri() for a ready full URL.
 *
 * @since 1.6.7
 * @param string $sku  Product SKU, e.g. 'br-006'.
 * @param string $view 'front' | 'back' | 'packshot'. Defaults to 'front'.
 * @return string Theme-relative URI (leading '/'), or '' on miss.
 */
function skyyrose_sot_product_image( $sku, $view = 'front' ) {
	$sku = sanitize_key( $sku );
	if ( '' === $sku ) {
		return '';
	}

	$chains = array(
		'front'    => array( 'front_model_image', 'image' ),
		'back'     => array( 'back_model_image', 'back_image' ),
		'packshot' => array( 'image', 'front_model_image' ),
	);
	$chain  = $chains[ $view ] ?? $chains['front'];

	// Collection comes from the product SOT (the catalog), so this stays correct
	// for any future SKU without a hardcoded prefix map.
	$product    = function_exists( 'skyyrose_get_product' ) ? skyyrose_get_product( $sku ) : null;
	$collection = is_array( $product ) ? ( $product['collection'] ?? '' ) : '';

	// 1. Preferred: the deployed collection sot.json imagery view.
	if ( '' !== $collection ) {
		$sot = skyyrose_get_collection_sot( $collection );
		if ( ! empty( $sot['products'] ) && is_array( $sot['products'] ) ) {
			foreach ( $sot['products'] as $entry ) {
				if ( ! is_array( $entry ) || ( $entry['sku'] ?? '' ) !== $sku ) {
					continue;
				}
				$images = isset( $entry['images'] ) && is_array( $entry['images'] ) ? $entry['images'] : array();
				foreach ( $chain as $slot ) {
					$resolved = $images[ $slot ]['resolved'] ?? '';
					if ( is_string( $resolved ) && '' !== $resolved ) {
						return '/' . ltrim( $resolved, '/' );
					}
				}
				break; // SKU matched but no slot in chain — fall through to CSV.
			}
		}
	}

	// 2. Fallback: catalog CSV columns. CSV paths are "assets/images/products/..";
	// strip the leading "assets" so the return matches the assets-relative convention.
	if ( is_array( $product ) ) {
		foreach ( $chain as $slot ) {
			$val = $product[ $slot ] ?? '';
			if ( is_string( $val ) && '' !== $val ) {
				return '/' . ltrim( preg_replace( '#^assets/#', '', $val ), '/' );
			}
		}
	}

	return '';
}

/**
 * Full URL for a per-SKU product image, with a placeholder on miss.
 *
 * Template-friendly wrapper around skyyrose_sot_product_image(): always returns
 * a valid URL, so a SOT miss degrades to the product placeholder rather than a
 * broken `SKYYROSE_ASSETS_URI . ''`.
 *
 * Usage: <img src="<?php echo esc_url( skyyrose_sot_product_image_uri( 'br-006', 'front' ) ); ?>">
 *
 * @since 1.6.7
 * @param string $sku  Product SKU.
 * @param string $view 'front' | 'back' | 'packshot'.
 * @return string Full image URL (never empty).
 */
function skyyrose_sot_product_image_uri( $sku, $view = 'front' ) {
	$rel = skyyrose_sot_product_image( $sku, $view );
	if ( '' === $rel ) {
		return get_theme_file_uri( 'assets/images/placeholder-product.jpg' );
	}
	return SKYYROSE_ASSETS_URI . $rel;
}
