<?php
/**
 * Skyy Mascot — Configuration, Customizer Controls, Guide-Brain Data
 *
 * Everything the "art-independent half" of the Skyy mascot system needs
 * that isn't the walk-on presentation JS/CSS itself:
 *   - Page-context resolution (shared by body_class, walkSide, and the
 *     per-page tip lookup so all three agree on "what page is this").
 *   - Customizer section: kill switch, GLB URL, LLM toggle, per-page tips.
 *   - data/site-guide.json loader (Tier 1 guide-brain data — generated by
 *     scripts/build-site-guide.py, never hand-edited).
 *
 * @package SkyyRose_Flagship
 * @since   7.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/*
--------------------------------------------------------------
 * Page Context
 *--------------------------------------------------------------*/

/**
 * Resolve which "Skyy context" the current request is in.
 *
 * Single source of truth for the mascot's conversational context — used by
 * the `data-context` attribute mascot.js keys its SCRIPTS object on, by the
 * `skyy-ctx-*` body class, by the walk-on side lookup, and by the per-page
 * tip Customizer fields. Existing context strings (homepage, preorder,
 * black-rose, love-hurts, signature, kids-capsule, 404, default) MUST stay
 * stable — mascot.js's SCRIPTS object is keyed on them.
 *
 * @since 7.1.0
 * @return string
 */
function skyyrose_get_skyy_context() {
	if ( is_front_page() ) {
		return 'homepage';
	}

	if ( is_page( 'pre-order' ) || is_page( 'preorder' ) ) {
		return 'preorder';
	}

	if ( is_page( 'faq' ) ) {
		return 'faq';
	}

	if ( is_page( 'shipping-returns' ) ) {
		return 'shipping-returns';
	}

	if ( function_exists( 'is_account_page' ) && is_account_page() ) {
		return 'my-account';
	}

	if ( is_404() ) {
		return '404';
	}

	$slug = get_queried_object() ? get_post_field( 'post_name', get_queried_object_id() ) : '';

	if ( str_contains( $slug, 'black-rose' ) ) {
		return 'black-rose';
	}

	if ( str_contains( $slug, 'love-hurts' ) ) {
		return 'love-hurts';
	}

	if ( str_contains( $slug, 'signature' ) ) {
		return 'signature';
	}

	if ( str_contains( $slug, 'kids-capsule' ) ) {
		return 'kids-capsule';
	}

	return 'default';
}

/**
 * Which side of the screen Skyy walks in from for a given context.
 *
 * Choreography per the mascot system scope: Love Hurts = right,
 * Black Rose = left, Signature = right. Contexts without a defined side
 * (kids-capsule, homepage, default, ...) use the right-side entrance —
 * the majority CSS case, keeping the mirrored-CSS surface minimal.
 *
 * @since 7.1.0
 * @param string $context Value returned by skyyrose_get_skyy_context().
 * @return string 'left' or 'right'.
 */
function skyyrose_get_skyy_walk_side( $context ) {
	return 'black-rose' === $context ? 'left' : 'right';
}

/*
--------------------------------------------------------------
 * Body Class
 *--------------------------------------------------------------*/

/**
 * Add a `skyy-ctx-{context}` body class so CSS/JS can target the current
 * mascot context without re-deriving it.
 *
 * @since 7.1.0
 * @param array $classes Existing body classes.
 * @return array
 */
function skyyrose_mascot_body_class( $classes ) {
	$classes[] = 'skyy-ctx-' . sanitize_html_class( skyyrose_get_skyy_context() );
	return $classes;
}
add_filter( 'body_class', 'skyyrose_mascot_body_class' );

/*
--------------------------------------------------------------
 * Guide-Brain Data (Tier 1 — deterministic, no LLM)
 *--------------------------------------------------------------*/

/**
 * Load data/site-guide.json — generated by scripts/build-site-guide.py from
 * the theme's own nav/page/catalog sources (never hand-edited).
 *
 * Memoized per request. Returns an empty {pages: {}, intents: []} shape if
 * the file is missing/corrupt so the mascot widget degrades to its static
 * SCRIPTS conversation trees instead of fataling.
 *
 * @since 7.1.0
 * @return array{pages: array, intents: array}
 */
function skyyrose_get_site_guide() {
	static $guide = null;

	if ( null !== $guide ) {
		return $guide;
	}

	$default = array(
		'pages'   => array(),
		'intents' => array(),
	);

	$path = get_theme_file_path( 'data/site-guide.json' );
	if ( ! is_readable( $path ) ) {
		$guide = $default;
		return $guide;
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local theme file read.
	$raw = file_get_contents( $path );
	if ( false === $raw || '' === $raw ) {
		$guide = $default;
		return $guide;
	}

	$decoded = json_decode( $raw, true );
	if ( ! is_array( $decoded ) || ! isset( $decoded['pages'], $decoded['intents'] ) ) {
		$guide = $default;
		return $guide;
	}

	$guide = array(
		'pages'   => is_array( $decoded['pages'] ) ? $decoded['pages'] : array(),
		'intents' => is_array( $decoded['intents'] ) ? $decoded['intents'] : array(),
	);

	return $guide;
}

/**
 * Founder/Customizer-authored tip for the current page context.
 *
 * Empty by default — renders only when configured (standing rule: no
 * founder-facing content ships without them writing it).
 *
 * @since 7.1.0
 * @return string
 */
function skyyrose_get_skyy_page_tip() {
	$context = skyyrose_get_skyy_context();
	$tip     = get_theme_mod( 'skyyrose_mascot_tip_' . $context, '' );
	return is_string( $tip ) ? trim( $tip ) : '';
}

/*
--------------------------------------------------------------
 * Live-On-Deploy Defaults
 *--------------------------------------------------------------*/

/**
 * Theme-shipped GLB URL — used as the Customizer field's default so the
 * 3D host is live the moment the theme deploys, with zero manual config.
 * An explicit Customizer value (including an intentionally emptied field)
 * always overrides this.
 *
 * @since 7.2.0
 * @return string Theme-relative GLB URL, or '' if the file isn't on disk.
 */
function skyyrose_get_default_skyy_glb_url() {
	static $default_url = null;

	if ( null !== $default_url ) {
		return $default_url;
	}

	$rel_path    = 'assets/models/skyy.glb';
	$default_url = file_exists( get_template_directory() . '/' . $rel_path )
		? get_template_directory_uri() . '/' . $rel_path
		: '';

	return $default_url;
}

/**
 * Is the Skyy mascot enabled? Defaults TRUE — the host ships live on
 * deploy; an explicit Customizer "Enable Skyy" = off still wins.
 *
 * @since 7.2.0
 * @return bool
 */
function skyyrose_mascot_is_enabled() {
	return (bool) get_theme_mod( 'skyyrose_mascot_enabled', true );
}

/**
 * Resolve the GLB URL Skyy should use: an explicit Customizer value, else
 * the theme-shipped model (skyyrose_get_default_skyy_glb_url()) when that
 * file exists on disk, else '' (2D sprite fallback).
 *
 * @since 7.2.0
 * @return string
 */
function skyyrose_get_skyy_glb_url() {
	$url = get_theme_mod( 'skyyrose_mascot_glb_url', skyyrose_get_default_skyy_glb_url() );
	return is_string( $url ) ? $url : '';
}

/*
--------------------------------------------------------------
 * Tier 2 Fallback — deterministic, no external API, no cost
 *--------------------------------------------------------------*/

/**
 * Keyword categories the Tier 1 guide-brain (data/site-guide.json) doesn't
 * cover: contact, about/founder, pricing, cart/checkout, account/login, and
 * greeting/identity. Pure server-side substring matching — no external API
 * call, no per-use cost. Consumed by skyyrose_ajax_mascot_chat() (see
 * inc/ajax-handlers.php) so the Tier 2 AJAX seam answers instead of always
 * returning an empty stub.
 *
 * @since 7.2.0
 * @return array<int, array{patterns: array<int, string>, answer: string, link: string}>
 */
function skyyrose_mascot_fallback_intents() {
	return array(
		array(
			'patterns' => array( 'contact', 'customer service', 'email', 'phone', 'reach you', 'get in touch' ),
			'answer'   => esc_html__( 'You can reach the SkyyRose team directly through our contact page. 🌹', 'skyyrose' ),
			'link'     => '/contact/',
		),
		array(
			'patterns' => array( 'about', 'story', 'founder', 'corey', 'who made this', 'who started' ),
			'answer'   => esc_html__( 'SkyyRose was built by Corey Foster from the ground up — Oakland roots, real luxury. Our story page has the full journey.', 'skyyrose' ),
			'link'     => '/about/',
		),
		array(
			'patterns' => array( 'price', 'cost', 'how much', 'expensive' ),
			'answer'   => esc_html__( 'Prices vary by piece — every product page shows the exact price and any pre-order details.', 'skyyrose' ),
			'link'     => '/shop/',
		),
		array(
			'patterns' => array( 'cart', 'checkout', 'discount', 'coupon', 'promo code', 'sale' ),
			'answer'   => esc_html__( 'You can review your bag and apply any code at checkout.', 'skyyrose' ),
			'link'     => '/cart/',
		),
		array(
			'patterns' => array( 'account', 'login', 'log in', 'sign in', 'sign up' ),
			'answer'   => esc_html__( 'Manage orders, addresses, and details from your account page.', 'skyyrose' ),
			'link'     => '/my-account/',
		),
		array(
			'patterns' => array( 'hi', 'hello', 'hey', 'who are you', 'what is your name', 'whats your name' ),
			'answer'   => esc_html__( 'Hey! I’m Skyy 👋 — ask me about sizing, shipping, pre-orders, or a collection.', 'skyyrose' ),
			'link'     => '',
		),
	);
}

/**
 * Match a free-text message against skyyrose_mascot_fallback_intents().
 * Mirrors mascot.js's client-side matchIntent() scoring (longer/more-specific
 * patterns outrank single-word ones) so server and client behave the same.
 *
 * @since 7.2.0
 * @param string $message Raw visitor message.
 * @return array{patterns: array, answer: string, link: string}|null
 */
function skyyrose_mascot_match_fallback_intent( $message ) {
	$normalized = strtolower( trim( preg_replace( '/[^\w\s\'-]/', ' ', (string) $message ) ) );
	if ( '' === $normalized ) {
		return null;
	}

	$best       = null;
	$best_score = 0;

	foreach ( skyyrose_mascot_fallback_intents() as $intent ) {
		$score = 0;
		foreach ( $intent['patterns'] as $pattern ) {
			// Word-boundary match, not plain substring — short tokens like
			// 'hi'/'hey'/'cost' would otherwise false-positive inside
			// unrelated words ('this', 'they', 'costume').
			if ( preg_match( '/\b' . preg_quote( $pattern, '/' ) . '\b/', $normalized ) ) {
				$score += substr_count( $pattern, ' ' ) + 1;
			}
		}
		if ( $score > $best_score ) {
			$best_score = $score;
			$best       = $intent;
		}
	}

	return $best;
}

/*
--------------------------------------------------------------
 * Customizer — Skyy Mascot
 *--------------------------------------------------------------*/

/**
 * Sanitize a Customizer checkbox value to a strict boolean.
 *
 * @since 7.1.0
 * @param mixed $value Raw checkbox value.
 * @return bool
 */
function skyyrose_sanitize_mascot_checkbox( $value ) {
	return (bool) $value;
}

/**
 * Register the "Skyy Mascot" Customizer section.
 *
 * Kept in its own hook (matches the klaviyo-integration.php pattern) rather
 * than growing inc/customizer.php — the mascot system is a self-contained
 * concern.
 *
 * @since 7.1.0
 * @param WP_Customize_Manager $wp_customize Theme Customizer object.
 * @return void
 */
function skyyrose_mascot_customize_register( $wp_customize ) {

	$wp_customize->add_section(
		'skyyrose_mascot',
		array(
			'title'       => esc_html__( 'Skyy Mascot', 'skyyrose' ),
			'description' => esc_html__( 'Living character widget — live sitewide by default (checkout excluded). Uncheck to take Skyy down.', 'skyyrose' ),
			'priority'    => 65,
		)
	);

	// Kill switch — live sitewide by default; explicitly unchecking still wins.
	$wp_customize->add_setting(
		'skyyrose_mascot_enabled',
		array(
			'default'           => true,
			'transport'         => 'refresh',
			'sanitize_callback' => 'skyyrose_sanitize_mascot_checkbox',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_enabled',
		array(
			'label'       => esc_html__( 'Enable Skyy', 'skyyrose' ),
			'description' => esc_html__( 'Shows the mascot widget sitewide (checkout always excluded).', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'checkbox',
		)
	);

	// GLB character model URL — defaults to the theme-shipped model
	// (assets/models/skyy.glb) when that file exists on disk; empty falls
	// back to the 2D sprite. An explicit Customizer value always overrides.
	$wp_customize->add_setting(
		'skyyrose_mascot_glb_url',
		array(
			'default'           => skyyrose_get_default_skyy_glb_url(),
			'transport'         => 'refresh',
			'sanitize_callback' => 'esc_url_raw',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_glb_url',
		array(
			'label'       => esc_html__( 'Character GLB URL', 'skyyrose' ),
			'description' => esc_html__( 'Rigged 3D model. Defaults to the theme-shipped model when present; leave empty to force the 2D sprite walk-on.', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'url',
		)
	);

	// Tier 2 expanded fallback — deterministic server-side keyword matching
	// (contact, about, pricing, account, greetings) beyond the 9 core Tier 1
	// intents. No external API call, no per-use cost — on by default.
	$wp_customize->add_setting(
		'skyyrose_mascot_llm_enabled',
		array(
			'default'           => true,
			'transport'         => 'refresh',
			'sanitize_callback' => 'skyyrose_sanitize_mascot_checkbox',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_llm_enabled',
		array(
			'label'       => esc_html__( 'Enable Expanded Fallback Answers (Tier 2)', 'skyyrose' ),
			'description' => esc_html__( 'Answers questions the scripted guide misses (contact, about, pricing, account) via deterministic server-side matching. No external API call, no per-use cost.', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'checkbox',
		)
	);

	// Per-page tips — empty by default, one line each, core pages only.
	$tip_pages = array(
		'homepage'         => esc_html__( 'Homepage Tip', 'skyyrose' ),
		'preorder'         => esc_html__( 'Pre-Order Page Tip', 'skyyrose' ),
		'black-rose'       => esc_html__( 'Black Rose Collection Tip', 'skyyrose' ),
		'love-hurts'       => esc_html__( 'Love Hurts Collection Tip', 'skyyrose' ),
		'signature'        => esc_html__( 'Signature Collection Tip', 'skyyrose' ),
		'kids-capsule'     => esc_html__( 'Kids Capsule Collection Tip', 'skyyrose' ),
		'faq'              => esc_html__( 'FAQ Page Tip', 'skyyrose' ),
		'shipping-returns' => esc_html__( 'Shipping & Returns Page Tip', 'skyyrose' ),
		'my-account'       => esc_html__( 'Account Page Tip', 'skyyrose' ),
	);

	foreach ( $tip_pages as $context => $label ) {
		$setting_id = 'skyyrose_mascot_tip_' . $context;

		$wp_customize->add_setting(
			$setting_id,
			array(
				'default'           => '',
				'transport'         => 'refresh',
				'sanitize_callback' => 'sanitize_text_field',
			)
		);
		$wp_customize->add_control(
			$setting_id,
			array(
				'label'       => $label,
				'description' => esc_html__( '1–2 lines. Empty = Skyy uses her default line here.', 'skyyrose' ),
				'section'     => 'skyyrose_mascot',
				'type'        => 'text',
			)
		);
	}
}
add_action( 'customize_register', 'skyyrose_mascot_customize_register' );
