<?php
/**
 * Skyy Mascot — Configuration, Customizer Controls, Guide-Brain Data
 *
 * Everything the "art-independent half" of the Skyy mascot system needs
 * that isn't the walk-on presentation JS/CSS itself:
 *   - Page-context resolution (shared by body_class, walkSide, and the
 *     per-page tip lookup so all three agree on "what page is this").
 *   - Customizer section: kill switch, GLB URL, LLM toggle, per-page tips.
 *   - data/site-guide.json loader (Tier 1 guide-brain data — generated by
 *     scripts/build-site-guide.py, never hand-edited).
 *
 * @package SkyyRose_Flagship
 * @since   7.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/*
--------------------------------------------------------------
 * Page Context
 *--------------------------------------------------------------*/

/**
 * Resolve which "Skyy context" the current request is in.
 *
 * Single source of truth for the mascot's conversational context — used by
 * the `data-context` attribute mascot.js keys its SCRIPTS object on, by the
 * `skyy-ctx-*` body class, by the walk-on side lookup, and by the per-page
 * tip Customizer fields. Existing context strings (homepage, preorder,
 * black-rose, love-hurts, signature, kids-capsule, 404, default) MUST stay
 * stable — mascot.js's SCRIPTS object is keyed on them.
 *
 * @since 7.1.0
 * @return string
 */
function skyyrose_get_skyy_context() {
	if ( is_front_page() ) {
		return 'homepage';
	}

	if ( is_page( 'pre-order' ) || is_page( 'preorder' ) ) {
		return 'preorder';
	}

	if ( is_page( 'faq' ) ) {
		return 'faq';
	}

	if ( is_page( 'shipping-returns' ) ) {
		return 'shipping-returns';
	}

	if ( function_exists( 'is_account_page' ) && is_account_page() ) {
		return 'my-account';
	}

	if ( is_404() ) {
		return '404';
	}

	$slug = get_queried_object() ? get_post_field( 'post_name', get_queried_object_id() ) : '';

	if ( str_contains( $slug, 'black-rose' ) ) {
		return 'black-rose';
	}

	if ( str_contains( $slug, 'love-hurts' ) ) {
		return 'love-hurts';
	}

	if ( str_contains( $slug, 'signature' ) ) {
		return 'signature';
	}

	if ( str_contains( $slug, 'kids-capsule' ) ) {
		return 'kids-capsule';
	}

	return 'default';
}

/**
 * Which side of the screen Skyy walks in from for a given context.
 *
 * Choreography per the mascot system scope: Love Hurts = right,
 * Black Rose = left, Signature = right. Contexts without a defined side
 * (kids-capsule, homepage, default, ...) use the right-side entrance —
 * the majority CSS case, keeping the mirrored-CSS surface minimal.
 *
 * @since 7.1.0
 * @param string $context Value returned by skyyrose_get_skyy_context().
 * @return string 'left' or 'right'.
 */
function skyyrose_get_skyy_walk_side( $context ) {
	return 'black-rose' === $context ? 'left' : 'right';
}

/*
--------------------------------------------------------------
 * Body Class
 *--------------------------------------------------------------*/

/**
 * Add a `skyy-ctx-{context}` body class so CSS/JS can target the current
 * mascot context without re-deriving it.
 *
 * @since 7.1.0
 * @param array $classes Existing body classes.
 * @return array
 */
function skyyrose_mascot_body_class( $classes ) {
	$classes[] = 'skyy-ctx-' . sanitize_html_class( skyyrose_get_skyy_context() );
	return $classes;
}
add_filter( 'body_class', 'skyyrose_mascot_body_class' );

/*
--------------------------------------------------------------
 * Guide-Brain Data (Tier 1 — deterministic, no LLM)
 *--------------------------------------------------------------*/

/**
 * Load data/site-guide.json — generated by scripts/build-site-guide.py from
 * the theme's own nav/page/catalog sources (never hand-edited).
 *
 * Memoized per request. Returns an empty {pages: {}, intents: []} shape if
 * the file is missing/corrupt so the mascot widget degrades to its static
 * SCRIPTS conversation trees instead of fataling.
 *
 * @since 7.1.0
 * @return array{pages: array, intents: array}
 */
function skyyrose_get_site_guide() {
	static $guide = null;

	if ( null !== $guide ) {
		return $guide;
	}

	$default = array(
		'pages'   => array(),
		'intents' => array(),
	);

	$path = get_theme_file_path( 'data/site-guide.json' );
	if ( ! is_readable( $path ) ) {
		$guide = $default;
		return $guide;
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local theme file read.
	$raw = file_get_contents( $path );
	if ( false === $raw || '' === $raw ) {
		$guide = $default;
		return $guide;
	}

	$decoded = json_decode( $raw, true );
	if ( ! is_array( $decoded ) || ! isset( $decoded['pages'], $decoded['intents'] ) ) {
		$guide = $default;
		return $guide;
	}

	$guide = array(
		'pages'   => is_array( $decoded['pages'] ) ? $decoded['pages'] : array(),
		'intents' => is_array( $decoded['intents'] ) ? $decoded['intents'] : array(),
	);

	return $guide;
}

/**
 * Founder/Customizer-authored tip for the current page context.
 *
 * Empty by default — renders only when configured (standing rule: no
 * founder-facing content ships without them writing it).
 *
 * @since 7.1.0
 * @return string
 */
function skyyrose_get_skyy_page_tip() {
	$context = skyyrose_get_skyy_context();
	$tip     = get_theme_mod( 'skyyrose_mascot_tip_' . $context, '' );
	return is_string( $tip ) ? trim( $tip ) : '';
}

/*
--------------------------------------------------------------
 * Customizer — Skyy Mascot
 *--------------------------------------------------------------*/

/**
 * Sanitize a Customizer checkbox value to a strict boolean.
 *
 * @since 7.1.0
 * @param mixed $value Raw checkbox value.
 * @return bool
 */
function skyyrose_sanitize_mascot_checkbox( $value ) {
	return (bool) $value;
}

/**
 * Register the "Skyy Mascot" Customizer section.
 *
 * Kept in its own hook (matches the klaviyo-integration.php pattern) rather
 * than growing inc/customizer.php — the mascot system is a self-contained
 * concern.
 *
 * @since 7.1.0
 * @param WP_Customize_Manager $wp_customize Theme Customizer object.
 * @return void
 */
function skyyrose_mascot_customize_register( $wp_customize ) {

	$wp_customize->add_section(
		'skyyrose_mascot',
		array(
			'title'       => esc_html__( 'Skyy Mascot', 'skyyrose' ),
			'description' => esc_html__( 'Living character widget — off by default until character art is finalized.', 'skyyrose' ),
			'priority'    => 65,
		)
	);

	// Kill switch — sitewide off by default.
	$wp_customize->add_setting(
		'skyyrose_mascot_enabled',
		array(
			'default'           => false,
			'transport'         => 'refresh',
			'sanitize_callback' => 'skyyrose_sanitize_mascot_checkbox',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_enabled',
		array(
			'label'       => esc_html__( 'Enable Skyy', 'skyyrose' ),
			'description' => esc_html__( 'Shows the mascot widget sitewide (checkout always excluded).', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'checkbox',
		)
	);

	// GLB character model URL — empty means the 2D sprite fallback renders.
	$wp_customize->add_setting(
		'skyyrose_mascot_glb_url',
		array(
			'default'           => '',
			'transport'         => 'refresh',
			'sanitize_callback' => 'esc_url_raw',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_glb_url',
		array(
			'label'       => esc_html__( 'Character GLB URL', 'skyyrose' ),
			'description' => esc_html__( 'Rigged 3D model. Leave empty to use the 2D sprite walk-on.', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'url',
		)
	);

	// Tier 2 LLM advice — off by default, paid per-use.
	$wp_customize->add_setting(
		'skyyrose_mascot_llm_enabled',
		array(
			'default'           => false,
			'transport'         => 'refresh',
			'sanitize_callback' => 'skyyrose_sanitize_mascot_checkbox',
		)
	);
	$wp_customize->add_control(
		'skyyrose_mascot_llm_enabled',
		array(
			'label'       => esc_html__( 'Enable LLM Advice (Tier 2)', 'skyyrose' ),
			'description' => esc_html__( 'Falls back to Claude for questions the scripted guide can\'t answer. Incurs per-use API cost.', 'skyyrose' ),
			'section'     => 'skyyrose_mascot',
			'type'        => 'checkbox',
		)
	);

	// Per-page tips — empty by default, one line each, core pages only.
	$tip_pages = array(
		'homepage'         => esc_html__( 'Homepage Tip', 'skyyrose' ),
		'preorder'         => esc_html__( 'Pre-Order Page Tip', 'skyyrose' ),
		'black-rose'       => esc_html__( 'Black Rose Collection Tip', 'skyyrose' ),
		'love-hurts'       => esc_html__( 'Love Hurts Collection Tip', 'skyyrose' ),
		'signature'        => esc_html__( 'Signature Collection Tip', 'skyyrose' ),
		'kids-capsule'     => esc_html__( 'Kids Capsule Collection Tip', 'skyyrose' ),
		'faq'              => esc_html__( 'FAQ Page Tip', 'skyyrose' ),
		'shipping-returns' => esc_html__( 'Shipping & Returns Page Tip', 'skyyrose' ),
		'my-account'       => esc_html__( 'Account Page Tip', 'skyyrose' ),
	);

	foreach ( $tip_pages as $context => $label ) {
		$setting_id = 'skyyrose_mascot_tip_' . $context;

		$wp_customize->add_setting(
			$setting_id,
			array(
				'default'           => '',
				'transport'         => 'refresh',
				'sanitize_callback' => 'sanitize_text_field',
			)
		);
		$wp_customize->add_control(
			$setting_id,
			array(
				'label'       => $label,
				'description' => esc_html__( '1–2 lines. Empty = Skyy uses her default line here.', 'skyyrose' ),
				'section'     => 'skyyrose_mascot',
				'type'        => 'text',
			)
		);
	}
}
add_action( 'customize_register', 'skyyrose_mascot_customize_register' );
