global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'devskyy-production'
    environment: 'production'

scrape_configs:
  - job_name: 'devskyy-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
