"""
WordPress 3D Viewer Plugin Generator
=======================================

Generates a WordPress plugin for displaying 3D models (GLB/GLTF)
using Three.js with AR support and SkyyRose branding.

Usage:
    from wordpress.threed_viewer_plugin import (
        ViewerConfig,
        WordPressPluginGenerator,
    )

    generator = WordPressPluginGenerator(output_dir=Path("./output"))
    plugin_dir = generator.generate()
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# =============================================================================
# Viewer Configuration
# =============================================================================


@dataclass
class ViewerConfig:
    """
    Configuration for the 3D model viewer.

    Controls camera, lighting, interaction, and AR settings.
    """

    # Camera
    camera_fov: float = 45.0
    camera_near: float = 0.1
    camera_far: float = 1000.0
    camera_position: tuple[float, float, float] = (0.0, 1.5, 3.0)

    # Controls
    auto_rotate: bool = True
    auto_rotate_speed: float = 2.0
    enable_zoom: bool = True
    enable_pan: bool = False
    min_distance: float = 1.0
    max_distance: float = 10.0

    # Lighting
    ambient_intensity: float = 0.5
    ambient_color: str = "#ffffff"
    directional_intensity: float = 0.8
    directional_color: str = "#ffffff"
    directional_position: tuple[float, float, float] = (5.0, 10.0, 7.5)

    # AR
    ar_enabled: bool = True
    ar_button_text: str = "View in Your Space"
    ar_button_color: str = "#B76E79"

    # UI
    loading_text: str = "Loading 3D Model..."
    background_color: str = "#0D0D0D"
    container_class: str = "skyyrose-3d-viewer"

    # Performance
    pixel_ratio: float = 1.5
    antialias: bool = True
    shadow_map: bool = True

    def to_dict(self) -> dict[str, Any]:
        """Convert config to camelCase dictionary for JavaScript consumption."""
        return {
            "cameraFov": self.camera_fov,
            "cameraNear": self.camera_near,
            "cameraFar": self.camera_far,
            "cameraPosition": list(self.camera_position),
            "autoRotate": self.auto_rotate,
            "autoRotateSpeed": self.auto_rotate_speed,
            "enableZoom": self.enable_zoom,
            "enablePan": self.enable_pan,
            "minDistance": self.min_distance,
            "maxDistance": self.max_distance,
            "ambientIntensity": self.ambient_intensity,
            "ambientColor": self.ambient_color,
            "directionalIntensity": self.directional_intensity,
            "directionalColor": self.directional_color,
            "directionalPosition": list(self.directional_position),
            "arEnabled": self.ar_enabled,
            "arButtonText": self.ar_button_text,
            "arButtonColor": self.ar_button_color,
            "loadingText": self.loading_text,
            "backgroundColor": self.background_color,
            "containerClass": self.container_class,
            "pixelRatio": self.pixel_ratio,
            "antialias": self.antialias,
            "shadowMap": self.shadow_map,
        }


# =============================================================================
# Code Generation Functions
# =============================================================================


def generate_viewer_javascript(config: ViewerConfig | None = None) -> str:
    """
    Generate Three.js viewer JavaScript code.

    Args:
        config: Viewer configuration. Uses defaults if not provided.

    Returns:
        JavaScript source code string.
    """
    if config is None:
        config = ViewerConfig()

    config_json = json.dumps(config.to_dict(), indent=2)

    return f"""/**
 * SkyyRose 3D Viewer - Three.js Integration
 * Where Love Meets Luxury
 *
 * Auto-generated by wordpress.threed_viewer_plugin
 */
(function() {{
  'use strict';

  const CONFIG = {config_json};

  class SkyyRoseViewer {{
    constructor(container, modelUrl) {{
      this.container = container;
      this.modelUrl = modelUrl;
      this.scene = null;
      this.camera = null;
      this.renderer = null;
      this.controls = null;
      this.model = null;
    }}

    init() {{
      this.setupScene();
      this.setupCamera();
      this.setupRenderer();
      this.setupLighting();
      this.setupControls();
      this.loadModel();
      this.animate();
    }}

    setupScene() {{
      this.scene = new THREE.Scene();
      this.scene.background = new THREE.Color(CONFIG.backgroundColor);
    }}

    setupCamera() {{
      const aspect = this.container.clientWidth / this.container.clientHeight;
      this.camera = new THREE.PerspectiveCamera(
        CONFIG.cameraFov, aspect, CONFIG.cameraNear, CONFIG.cameraFar
      );
      this.camera.position.set(...CONFIG.cameraPosition);
    }}

    setupRenderer() {{
      this.renderer = new THREE.WebGLRenderer({{
        antialias: CONFIG.antialias,
        alpha: true
      }});
      this.renderer.setSize(this.container.clientWidth, this.container.clientHeight);
      this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, CONFIG.pixelRatio));
      if (CONFIG.shadowMap) {{
        this.renderer.shadowMap.enabled = true;
        this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
      }}
      this.container.appendChild(this.renderer.domElement);
    }}

    setupLighting() {{
      const ambient = new THREE.AmbientLight(CONFIG.ambientColor, CONFIG.ambientIntensity);
      this.scene.add(ambient);

      const directional = new THREE.DirectionalLight(
        CONFIG.directionalColor, CONFIG.directionalIntensity
      );
      directional.position.set(...CONFIG.directionalPosition);
      directional.castShadow = CONFIG.shadowMap;
      this.scene.add(directional);
    }}

    setupControls() {{
      if (typeof THREE.OrbitControls !== 'undefined') {{
        this.controls = new THREE.OrbitControls(this.camera, this.renderer.domElement);
        this.controls.autoRotate = CONFIG.autoRotate;
        this.controls.autoRotateSpeed = CONFIG.autoRotateSpeed;
        this.controls.enableZoom = CONFIG.enableZoom;
        this.controls.enablePan = CONFIG.enablePan;
        this.controls.minDistance = CONFIG.minDistance;
        this.controls.maxDistance = CONFIG.maxDistance;
      }}
    }}

    loadModel() {{
      if (typeof THREE.GLTFLoader !== 'undefined') {{
        const loader = new THREE.GLTFLoader();
        loader.load(
          this.modelUrl,
          (gltf) => {{
            this.model = gltf.scene;
            this.scene.add(this.model);
            this.centerModel();
          }},
          (progress) => {{
            const pct = (progress.loaded / progress.total * 100).toFixed(0);
            this.updateLoading(pct);
          }},
          (error) => {{
            console.error('Model load error:', error);
          }}
        );
      }}
    }}

    centerModel() {{
      if (!this.model) return;
      const box = new THREE.Box3().setFromObject(this.model);
      const center = box.getCenter(new THREE.Vector3());
      this.model.position.sub(center);
    }}

    updateLoading(percentage) {{
      const loader = this.container.querySelector('.loading-indicator');
      if (loader) {{
        loader.textContent = CONFIG.loadingText + ' ' + percentage + '%';
      }}
    }}

    animate() {{
      requestAnimationFrame(() => this.animate());
      if (this.controls) this.controls.update();
      this.render();
    }}

    render() {{
      if (this.renderer && this.scene && this.camera) {{
        this.renderer.render(this.scene, this.camera);
      }}
    }}

    dispose() {{
      if (this.renderer) {{
        this.renderer.dispose();
      }}
    }}
  }}

  // Auto-initialize viewers on page load
  document.addEventListener('DOMContentLoaded', function() {{
    const containers = document.querySelectorAll('.' + CONFIG.containerClass);
    containers.forEach(function(container) {{
      const modelUrl = container.dataset.modelUrl;
      if (modelUrl) {{
        const viewer = new SkyyRoseViewer(container, modelUrl);
        viewer.init();
      }}
    }});
  }});

  // Expose for external use
  window.SkyyRoseViewer = SkyyRoseViewer;
}})();
"""


def generate_viewer_css() -> str:
    """
    Generate CSS styles for the 3D viewer.

    Returns:
        CSS source code string.
    """
    return """.skyyrose-3d-viewer {
  width: 100%;
  height: 600px;
  position: relative;
  overflow: hidden;
  background-color: #0D0D0D;
  border-radius: 4px;
}

.skyyrose-3d-viewer canvas {
  width: 100%;
  height: 100%;
  display: block;
}

.skyyrose-3d-viewer .loading-indicator {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: #B76E79;
  font-family: 'Inter', sans-serif;
  font-size: 14px;
  letter-spacing: 2px;
  text-transform: uppercase;
}

.skyyrose-3d-viewer .ar-button {
  position: absolute;
  bottom: 20px;
  right: 20px;
  padding: 12px 24px;
  background-color: #B76E79;
  color: #FAFAFA;
  border: none;
  border-radius: 0;
  font-family: 'Inter', sans-serif;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 2px;
  text-transform: uppercase;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.skyyrose-3d-viewer .ar-button:hover {
  background-color: #A25D68;
}

.skyyrose-3d-viewer .controls-hint {
  position: absolute;
  bottom: 20px;
  left: 20px;
  color: rgba(255, 255, 255, 0.5);
  font-family: 'Inter', sans-serif;
  font-size: 11px;
  letter-spacing: 1px;
}

@media (max-width: 768px) {
  .skyyrose-3d-viewer {
    height: 400px;
  }

  .skyyrose-3d-viewer .ar-button {
    bottom: 10px;
    right: 10px;
    padding: 8px 16px;
    font-size: 11px;
  }
}
"""


def generate_shortcode_html(
    model_url: str = "",
    width: str = "100%",
    height: str = "600px",
) -> str:
    """
    Generate HTML for a WordPress shortcode embedding a 3D viewer.

    Args:
        model_url: URL to the GLB/GLTF model file.
        width: Container width (CSS value).
        height: Container height (CSS value).

    Returns:
        HTML string for the viewer shortcode.
    """
    return (
        f'<div class="skyyrose-3d-viewer" '
        f'data-model-url="{model_url}" '
        f'style="width: {width}; height: {height};">'
        f'<div class="loading-indicator">Loading 3D Model...</div>'
        f"</div>"
    )


# =============================================================================
# Plugin Generator
# =============================================================================


class WordPressPluginGenerator:
    """
    Generates a complete WordPress plugin directory for the 3D viewer.

    Creates the directory structure with JavaScript, CSS, and config files
    ready for installation in WordPress.

    Usage:
        generator = WordPressPluginGenerator(output_dir=Path("./output"))
        plugin_dir = generator.generate()
    """

    def __init__(
        self,
        output_dir: Path | str = Path("."),
        plugin_name: str = "skyyrose-3d-viewer",
        version: str = "1.0.0",
    ) -> None:
        """
        Initialize plugin generator.

        Args:
            output_dir: Root directory for plugin output.
            plugin_name: WordPress plugin slug/directory name.
            version: Plugin version string.
        """
        self.output_dir = Path(output_dir)
        self.plugin_name = plugin_name
        self.version = version
        self.config = ViewerConfig()

    def generate(self) -> Path:
        """
        Generate the complete plugin directory structure.

        Returns:
            Path to the generated plugin directory.
        """
        plugin_dir = self.output_dir / self.plugin_name

        # Create directory structure
        js_dir = plugin_dir / "assets" / "js"
        css_dir = plugin_dir / "assets" / "css"
        js_dir.mkdir(parents=True, exist_ok=True)
        css_dir.mkdir(parents=True, exist_ok=True)

        # Generate files
        js_file = js_dir / "3d-viewer.js"
        js_file.write_text(generate_viewer_javascript(self.config))

        css_file = css_dir / "3d-viewer.css"
        css_file.write_text(generate_viewer_css())

        config_file = plugin_dir / "config.json"
        config_file.write_text(json.dumps(self.config.to_dict(), indent=2))

        # Generate main plugin PHP file
        php_file = plugin_dir / f"{self.plugin_name}.php"
        php_file.write_text(self._generate_plugin_php())

        logger.info(
            "plugin_generated",
            extra={
                "plugin_name": self.plugin_name,
                "version": self.version,
                "path": str(plugin_dir),
            },
        )

        return plugin_dir

    def _generate_plugin_php(self) -> str:
        """Generate the main WordPress plugin PHP file."""
        return f"""<?php
/**
 * Plugin Name: {self.plugin_name}
 * Description: 3D model viewer for SkyyRose luxury fashion products
 * Version: {self.version}
 * Author: SkyyRose LLC
 * License: Proprietary
 */

if (!defined('ABSPATH')) exit;

class SkyyRose_3D_Viewer {{
    public function __construct() {{
        add_action('wp_enqueue_scripts', [$this, 'enqueue_assets']);
        add_shortcode('skyyrose_3d', [$this, 'render_shortcode']);
    }}

    public function enqueue_assets() {{
        wp_enqueue_script(
            'three-js',
            'https://unpkg.com/three@0.160.0/build/three.min.js',
            [],
            '0.160.0',
            true
        );
        wp_enqueue_script(
            '{self.plugin_name}',
            plugin_dir_url(__FILE__) . 'assets/js/3d-viewer.js',
            ['three-js'],
            '{self.version}',
            true
        );
        wp_enqueue_style(
            '{self.plugin_name}',
            plugin_dir_url(__FILE__) . 'assets/css/3d-viewer.css',
            [],
            '{self.version}'
        );
    }}

    public function render_shortcode($atts) {{
        $atts = shortcode_atts([
            'model_url' => '',
            'width' => '100%',
            'height' => '600px',
        ], $atts);

        return '<div class="skyyrose-3d-viewer" '
            . 'data-model-url="' . esc_url($atts['model_url']) . '" '
            . 'style="width: ' . esc_attr($atts['width']) . '; height: ' . esc_attr($atts['height']) . ';">'
            . '<div class="loading-indicator">Loading 3D Model...</div>'
            . '</div>';
    }}
}}

new SkyyRose_3D_Viewer();
"""


# Backwards-compatible aliases
PluginGenerator = WordPressPluginGenerator
ThreeDViewerPlugin = WordPressPluginGenerator


__all__ = [
    "ViewerConfig",
    "WordPressPluginGenerator",
    "PluginGenerator",
    "ThreeDViewerPlugin",
    "generate_viewer_javascript",
    "generate_viewer_css",
    "generate_shortcode_html",
]
