#!/usr/bin/env python3
"""Audit golden-reference coverage across every active SKU.

Outputs ``tasks/golden-coverage-report.md`` with a per-SKU coverage matrix
and aggregate summary. Optionally fails CI on coverage thresholds.

Usage:
  python scripts/audit_golden_coverage.py
  python scripts/audit_golden_coverage.py --strict        # exit 2 if any SKU has 0 goldens
  python scripts/audit_golden_coverage.py --json          # machine-readable
  python scripts/audit_golden_coverage.py --sku br-001    # single SKU

Exit:
  0 success
  1 audit error
  2 strict mode and any active SKU has 0 goldens
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from skyyrose.core.catalog_loader import read_catalog_rows  # noqa: E402
from skyyrose.elite_studio.quality.visual_regression import (  # noqa: E402
    CANONICAL_ANGLES,
    VisualRegressionTester,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Golden coverage audit")
    parser.add_argument("--strict", action="store_true", help="Fail on any zero-coverage SKU")
    parser.add_argument("--json", action="store_true", help="Emit JSON to stdout")
    parser.add_argument(
        "--sku",
        help="Audit only one SKU (default: every row in canonical CSV)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(ROOT / "tasks" / "golden-coverage-report.md"),
        help="Markdown report destination",
    )
    args = parser.parse_args()

    rows = read_catalog_rows()
    if args.sku:
        rows = [r for r in rows if r.get("sku") == args.sku]
        if not rows:
            print(f"✗ {args.sku} is not in the catalog", file=sys.stderr)
            return 1

    tester = VisualRegressionTester()
    per_sku: list[dict] = []
    zero_coverage: list[str] = []
    full_coverage: list[str] = []

    for row in rows:
        sku = row.get("sku")
        if not sku:
            continue
        cov = tester.coverage_for(sku)
        present = sum(1 for v in cov.values() if v)
        if present == 0:
            zero_coverage.append(sku)
        if present == len(CANONICAL_ANGLES):
            full_coverage.append(sku)
        per_sku.append(
            {
                "sku": sku,
                "name": row.get("name", ""),
                "collection": row.get("collection", ""),
                "angles": cov,
                "present": present,
                "total": len(CANONICAL_ANGLES),
                "coverage_pct": round(100 * present / len(CANONICAL_ANGLES), 1),
            }
        )

    summary = {
        "total_active_skus": len(per_sku),
        "skus_with_full_coverage": len(full_coverage),
        "skus_with_zero_coverage": len(zero_coverage),
        "average_coverage_pct": round(
            sum(s["coverage_pct"] for s in per_sku) / max(1, len(per_sku)), 1
        ),
        "zero_coverage_skus": zero_coverage,
        "full_coverage_skus": full_coverage,
    }

    if args.json:
        print(json.dumps({"summary": summary, "per_sku": per_sku}, indent=2))
    else:
        report = _render_markdown(per_sku, summary)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report)
        print(f"Wrote audit to {args.output}")
        print(
            f"  ✓ {summary['skus_with_full_coverage']}/{summary['total_active_skus']} "
            f"SKUs at full {len(CANONICAL_ANGLES)}-angle coverage "
            f"(avg {summary['average_coverage_pct']}%, "
            f"{summary['skus_with_zero_coverage']} zero-coverage)"
        )

    if args.strict and summary["skus_with_zero_coverage"] > 0:
        return 2
    return 0


def _render_markdown(per_sku, summary):
    lines = [
        "# Golden Reference Coverage Audit",
        "",
        "Auto-generated by `scripts/audit_golden_coverage.py`. ",
        "Goldens live at `skyyrose/elite_studio/assets/golden/{sku}/{angle}.jpg`. ",
        "Per-angle SSIM thresholds: front/back=0.85, three-quarter=0.78, detail-1/2=0.92.",
        "",
        "## Summary",
        "",
        f"- Total active SKUs: **{summary['total_active_skus']}**",
        f"- Full coverage ({len(CANONICAL_ANGLES)} angles): **{summary['skus_with_full_coverage']}**",
        f"- Zero coverage: **{summary['skus_with_zero_coverage']}**",
        f"- Average coverage: **{summary['average_coverage_pct']}%**",
        "",
    ]
    if summary["zero_coverage_skus"]:
        lines += [
            "## SKUs with Zero Goldens (sourcing required)",
            "",
        ]
        for sku in summary["zero_coverage_skus"]:
            lines.append(f"- `{sku}`")
        lines.append("")

    lines += [
        "## Per-SKU Coverage Matrix",
        "",
        "| SKU | Name | Collection | " + " | ".join(CANONICAL_ANGLES) + " | Coverage |",
        "|-----|------|------------|" + "|".join(["-----"] * (len(CANONICAL_ANGLES) + 1)) + "|",
    ]
    for s in sorted(per_sku, key=lambda r: (r["collection"], r["sku"])):
        cells = ["✓" if s["angles"][a] else "—" for a in CANONICAL_ANGLES]
        lines.append(
            f"| `{s['sku']}` | {s['name']} | {s['collection']} | "
            + " | ".join(cells)
            + f" | {s['coverage_pct']}% |"
        )
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
