#!/usr/bin/env python3
"""Audit dossier completeness across every active SKU in the canonical CSV.

Outputs a markdown report at ``tasks/dossier-audit-report.md`` with:
  * one row per SKU: region count, hex/Pantone coverage %, warnings
  * an aggregate summary footer

Exit code:
  0 — every dossier passes schema (warnings allowed)
  1 — at least one dossier fails schema or is missing
  2 — strict mode (`--strict`) and any warning present

Usage:
  python scripts/audit_dossier_coverage.py
  python scripts/audit_dossier_coverage.py --strict --json
  python scripts/audit_dossier_coverage.py --output /tmp/report.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Allow running from the repo root without `pip install -e .`
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from skyyrose.core.catalog_loader import read_catalog_rows  # noqa: E402
from skyyrose.core.dossier_loader import DossierMissingError  # noqa: E402
from skyyrose.core.dossier_schema import (  # noqa: E402
    DossierSchemaError,
    coverage_for,
    load_validated_for_sku,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Dossier coverage audit")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero on any warning (not just schema failures)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON to stdout instead of markdown",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(ROOT / "tasks" / "dossier-audit-report.md"),
        help="Markdown report destination (default: tasks/dossier-audit-report.md)",
    )
    args = parser.parse_args()

    rows = read_catalog_rows()
    coverages = []
    failures: list[tuple[str, str]] = []

    for row in rows:
        sku = row["sku"]
        if not sku:
            continue
        try:
            schema = load_validated_for_sku(sku)
        except DossierMissingError as exc:
            failures.append((sku, f"MISSING: {exc}"))
            continue
        except DossierSchemaError as exc:
            failures.append((sku, f"SCHEMA: {exc}"))
            continue
        except Exception as exc:  # pragma: no cover
            failures.append((sku, f"ERROR: {exc}"))
            continue
        coverages.append(coverage_for(schema))

    summary = _summarize(coverages, failures)

    if args.json:
        body = {
            "summary": summary,
            "coverages": [c.to_dict() for c in coverages],
            "failures": [{"sku": s, "reason": r} for s, r in failures],
        }
        print(json.dumps(body, indent=2))
    else:
        report = _render_markdown(coverages, failures, summary)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report)
        print(f"Wrote audit to {args.output}")
        print(_render_summary_text(summary))

    if failures:
        return 1
    if args.strict and any(c.warnings for c in coverages):
        return 2
    return 0


def _summarize(coverages, failures):
    total = len(coverages) + len(failures)
    avg_hex = (
        round(sum(c.hex_coverage_pct for c in coverages) / len(coverages), 1) if coverages else 0.0
    )
    avg_pantone = (
        round(sum(c.pantone_coverage_pct for c in coverages) / len(coverages), 1)
        if coverages
        else 0.0
    )
    avg_regions = (
        round(sum(c.region_count for c in coverages) / len(coverages), 1) if coverages else 0.0
    )
    warned = sum(1 for c in coverages if c.warnings)
    return {
        "total_active_skus": total,
        "passing_schema": len(coverages),
        "failing_schema": len(failures),
        "avg_hex_coverage_pct": avg_hex,
        "avg_pantone_coverage_pct": avg_pantone,
        "avg_regions_per_dossier": avg_regions,
        "skus_with_warnings": warned,
    }


def _render_markdown(coverages, failures, summary):
    lines = [
        "# Dossier Coverage Audit",
        "",
        "Auto-generated by `scripts/audit_dossier_coverage.py`. ",
        "Schema lives at `skyyrose/core/dossier_schema.py`.",
        "",
        "## Summary",
        "",
        f"- Total active SKUs: **{summary['total_active_skus']}**",
        f"- Passing schema: **{summary['passing_schema']}**",
        f"- Failing schema: **{summary['failing_schema']}**",
        f"- Average regions per dossier: **{summary['avg_regions_per_dossier']}**",
        f"- Average hex-color coverage: **{summary['avg_hex_coverage_pct']}%**",
        f"- Average Pantone coverage: **{summary['avg_pantone_coverage_pct']}%**",
        f"- SKUs with warnings: **{summary['skus_with_warnings']}**",
        "",
    ]
    if failures:
        lines += ["## Failures", "", "| SKU | Reason |", "|-----|--------|"]
        for sku, reason in failures:
            lines.append(f"| `{sku}` | {reason.replace('|', '\\|')[:120]} |")
        lines.append("")

    lines += [
        "## Per-SKU Coverage",
        "",
        "| SKU | Name | Collection | Regions | Hex % | Pantone % | Warnings |",
        "|-----|------|------------|---------|-------|-----------|----------|",
    ]
    for c in sorted(coverages, key=lambda c: (c.collection, c.sku)):
        warns = "; ".join(c.warnings) if c.warnings else "—"
        lines.append(
            f"| `{c.sku}` | {c.name} | {c.collection} | "
            f"{c.region_count} | {c.hex_coverage_pct}% | "
            f"{c.pantone_coverage_pct}% | {warns} |"
        )
    lines.append("")
    return "\n".join(lines)


def _render_summary_text(summary):
    return (
        f"  ✓ {summary['passing_schema']}/{summary['total_active_skus']} "
        f"dossiers pass schema "
        f"(avg {summary['avg_regions_per_dossier']} regions, "
        f"avg hex {summary['avg_hex_coverage_pct']}%, "
        f"warnings on {summary['skus_with_warnings']})"
    )


if __name__ == "__main__":
    raise SystemExit(main())
