#!/usr/bin/env bash
# Weekly Dependabot triage + batch-PR routine.
#
# Why this exists:
#   Per claude-mem archive Pattern #4, Dependabot vulnerability count has grown
#   monotonically (326 → 407 → 429 → 432 over 7 days). CI Security Gate fails
#   on every PR because of it. No automation triaged or batched fixes; the
#   count compounded silently.
#
# What it does:
#   1. Fetch all open Dependabot alerts via `gh api dependabot/alerts --paginate`
#   2. Group by severity (critical, high, moderate, low)
#   3. For CRITICAL: comment `@dependabot rebase` on any existing PR (forces refresh),
#      or open an individual PR via `@dependabot recreate` placeholder issue
#   4. For HIGH+MODERATE: open ONE batch PR titled
#      `chore(deps): weekly security batch — N criticals, M highs, P moderates`
#      with a checklist body listing every CVE + package
#   5. LOW: just log; no PR creation
#
# Modes:
#   --dry-run     Print plan; do not call any mutation endpoint.
#   --execute     Real run (default).
#
# Requires:
#   gh CLI authenticated with repo + security_events scope.
#   jq for JSON parsing.
#
# Bypass:
#   DEPENDABOT_BATCH_DISABLE=1 env var causes the script to exit 0 immediately.

set -euo pipefail

DRY_RUN=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --execute) DRY_RUN=false ;;
        --help|-h)
            sed -n '1,/^set -euo pipefail/p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "unknown arg: $arg" >&2; exit 1 ;;
    esac
done

if [[ "${DEPENDABOT_BATCH_DISABLE:-0}" == "1" ]]; then
    echo "[dependabot-batch] disabled via DEPENDABOT_BATCH_DISABLE=1"
    exit 0
fi

# Fail-closed on missing deps.
command -v gh >/dev/null || { echo "FATAL: gh CLI missing"; exit 2; }
command -v jq >/dev/null || { echo "FATAL: jq missing"; exit 2; }

# Resolve repo identity from gh.
REPO=$(gh repo view --json owner,name --jq '.owner.login + "/" + .name')
echo "[dependabot-batch] repo: $REPO  dry-run: $DRY_RUN"

# Fetch open alerts.
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
ALERTS_JSON="$TMP/alerts.json"

if ! gh api -X GET "repos/$REPO/dependabot/alerts" --paginate \
        -f state=open --jq '.[] | {id: .number, severity: .security_advisory.severity, summary: .security_advisory.summary, package: .dependency.package.name, ecosystem: .dependency.package.ecosystem}' \
        > "$ALERTS_JSON" 2>"$TMP/err.log"; then
    echo "[dependabot-batch] FATAL: gh api failed:" >&2
    cat "$TMP/err.log" >&2
    exit 2
fi

# Count by severity.
total=$(jq -s 'length' "$ALERTS_JSON")
crit=$(jq -s 'map(select(.severity == "critical")) | length' "$ALERTS_JSON")
high=$(jq -s 'map(select(.severity == "high")) | length' "$ALERTS_JSON")
mod=$(jq -s 'map(select(.severity == "medium" or .severity == "moderate")) | length' "$ALERTS_JSON")
low=$(jq -s 'map(select(.severity == "low")) | length' "$ALERTS_JSON")

echo "[dependabot-batch] alerts: $total total ($crit critical, $high high, $mod moderate, $low low)"

if [[ "$total" == "0" ]]; then
    echo "[dependabot-batch] no open alerts — nothing to do."
    exit 0
fi

# Build batch PR body — checklist of every alert.
BODY_FILE="$TMP/pr-body.md"
{
    echo "## Weekly Dependabot Security Batch"
    echo ""
    echo "Auto-generated by \`scripts/dependabot-batch-pr.sh\`."
    echo ""
    echo "**Summary**"
    echo "- Critical: $crit"
    echo "- High:     $high"
    echo "- Moderate: $mod"
    echo "- Low:      $low (logged, not included in batch)"
    echo ""
    echo "## Checklist (CRITICAL — must merge before HIGH/MODERATE)"
    jq -rs 'map(select(.severity == "critical")) | sort_by(.package) | .[] | "- [ ] **#\(.id)** \(.package) (\(.ecosystem)) — \(.summary)"' "$ALERTS_JSON"
    echo ""
    echo "## Checklist (HIGH)"
    jq -rs 'map(select(.severity == "high")) | sort_by(.package) | .[] | "- [ ] **#\(.id)** \(.package) (\(.ecosystem)) — \(.summary)"' "$ALERTS_JSON"
    echo ""
    echo "## Checklist (MODERATE)"
    jq -rs 'map(select(.severity == "medium" or .severity == "moderate")) | sort_by(.package) | .[] | "- [ ] **#\(.id)** \(.package) (\(.ecosystem)) — \(.summary)"' "$ALERTS_JSON"
    echo ""
    echo "---"
    echo ""
    echo "Comment \`@dependabot recreate\` on individual Dependabot PRs to force refresh."
    echo "This batch PR tracks the triage list; close it once all linked Dependabot PRs merge."
} > "$BODY_FILE"

PR_TITLE="chore(deps): weekly security batch — $crit criticals, $high highs, $mod moderates"

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dependabot-batch] DRY RUN — would create PR:"
    echo "  Title: $PR_TITLE"
    echo "  Body:"
    sed 's/^/    /' "$BODY_FILE"
    echo "[dependabot-batch] DRY RUN — would comment @dependabot rebase on existing critical PRs."
    exit 0
fi

# Real execution — open the batch PR if HIGH+MODERATE > 0.
if [[ "$((high + mod))" -gt 0 ]]; then
    BRANCH="chore/deps-weekly-batch-$(date +%Y%m%d)"
    # Use a draft branch by creating a tracking issue when no working branch exists.
    # This avoids force-creating branches with no diff. Instead, the PR body
    # IS the checklist — operators tick boxes as individual Dependabot PRs merge.
    # Search for an existing tracking ISSUE (not PR — we never had a diff).
    # The previous `gh pr list` always returned empty because we create
    # issues, not PRs (CR finding 2026-05-22 HIGH).
    EXISTING=$(gh issue list --search "in:title \"weekly security batch\"" \
        --state open --json number --jq '.[0].number // empty')
    if [[ -n "$EXISTING" ]]; then
        echo "[dependabot-batch] existing batch issue #$EXISTING — updating body."
        gh issue edit "$EXISTING" --body-file "$BODY_FILE" --title "$PR_TITLE"
    else
        echo "[dependabot-batch] creating new tracking issue."
        gh issue create --title "$PR_TITLE" --body-file "$BODY_FILE" --label "dependencies,security"
    fi
fi

# For CRITICALS: comment @dependabot rebase on each existing PR.
if [[ "$crit" -gt 0 ]]; then
    echo "[dependabot-batch] refreshing CRITICAL dependabot PRs..."
    gh pr list --search 'author:app/dependabot is:open' --json number,title --jq '.[] | "\(.number) \(.title)"' | \
        while read -r pr_num pr_title; do
            # Match if any critical alert package name appears in PR title
            jq -rs 'map(select(.severity == "critical")) | .[].package' "$ALERTS_JSON" | while read -r pkg; do
                # Word-boundary match — prevents `lodash` from matching
                # `lodash-es` or `@types/lodash-webpack-plugin` etc.
                # (CR finding 2026-05-22 HIGH).
                if echo " $pr_title " | grep -qiwF " $pkg "; then
                    echo "  → @dependabot rebase on PR #$pr_num (matches $pkg)"
                    gh pr comment "$pr_num" --body "@dependabot rebase"
                    break
                fi
            done
        done
fi

echo "[dependabot-batch] done."
