#!/bin/bash

#
# Setup DevSkyy MCP for critical-fuchsia-ape Backend
#
# Usage:
#   ./scripts/setup_critical_fuchsia_ape.sh [URL] [KEY]
#
# Examples:
#   ./scripts/setup_critical_fuchsia_ape.sh
#   ./scripts/setup_critical_fuchsia_ape.sh http://critical-fuchsia-ape:8000 sk-xxx
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
ENV_EXAMPLE="$PROJECT_ROOT/mcp/.env.example"

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}DevSkyy MCP - Critical Fuchsia Ape Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

# Parse arguments
API_URL="${1:-http://critical-fuchsia-ape:8000}"
API_KEY="${2:-}"

# If no API key provided, prompt for it
if [ -z "$API_KEY" ]; then
    echo -e "${YELLOW}Enter your critical-fuchsia-ape API key:${NC}"
    read -s API_KEY
    echo ""
fi

if [ -z "$API_KEY" ]; then
    echo -e "${RED}✗ API key is required${NC}"
    exit 1
fi

# Step 1: Check dependencies
echo -e "${BLUE}Step 1: Checking dependencies...${NC}"
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}✗ Python 3 not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python 3 found${NC}"

# Step 2: Create/update .env file
echo -e "\n${BLUE}Step 2: Creating .env file...${NC}"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠ .env file already exists${NC}"
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Skipping .env creation${NC}"
    else
        cat > "$ENV_FILE" << EOF
# DevSkyy MCP Configuration - Critical Fuchsia Ape Backend
# Generated by setup_critical_fuchsia_ape.sh

# Backend selection
MCP_BACKEND=critical-fuchsia-ape

# Critical Fuchsia Ape Configuration
CRITICAL_FUCHSIA_APE_URL=$API_URL
CRITICAL_FUCHSIA_APE_KEY=$API_KEY

# Default DevSkyy backend (if needed for fallback)
DEVSKYY_API_URL=http://localhost:8000
DEVSKYY_API_KEY=your-fallback-key

# Other configuration (from mcp/.env.example)
ENVIRONMENT=production
DEBUG=false
EOF
        echo -e "${GREEN}✓ .env file created${NC}"
    fi
else
    cat > "$ENV_FILE" << EOF
# DevSkyy MCP Configuration - Critical Fuchsia Ape Backend
# Generated by setup_critical_fuchsia_ape.sh

# Backend selection
MCP_BACKEND=critical-fuchsia-ape

# Critical Fuchsia Ape Configuration
CRITICAL_FUCHSIA_APE_URL=$API_URL
CRITICAL_FUCHSIA_APE_KEY=$API_KEY

# Default DevSkyy backend (if needed for fallback)
DEVSKYY_API_URL=http://localhost:8000
DEVSKYY_API_KEY=your-fallback-key

# Other configuration (from mcp/.env.example)
ENVIRONMENT=production
DEBUG=false
EOF
    echo -e "${GREEN}✓ .env file created${NC}"
fi

# Step 3: Install Python dependencies
echo -e "\n${BLUE}Step 3: Installing Python dependencies...${NC}"
if [ -f "$PROJECT_ROOT/mcp/requirements.txt" ]; then
    pip3 install -q -r "$PROJECT_ROOT/mcp/requirements.txt"
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${YELLOW}⚠ requirements.txt not found, skipping pip install${NC}"
fi

# Step 4: Test connectivity
echo -e "\n${BLUE}Step 4: Testing connectivity to critical-fuchsia-ape...${NC}"

# Check if API endpoint is reachable
if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "Authorization: Bearer $API_KEY" \
        "$API_URL/health" 2>/dev/null || echo "000")
    
    if [ "$HTTP_CODE" = "200" ]; then
        echo -e "${GREEN}✓ Successfully connected to $API_URL${NC}"
    elif [ "$HTTP_CODE" = "401" ]; then
        echo -e "${YELLOW}⚠ API key might be invalid (HTTP 401)${NC}"
    elif [ "$HTTP_CODE" = "000" ]; then
        echo -e "${YELLOW}⚠ Could not reach $API_URL (network issue or server down)${NC}"
    else
        echo -e "${YELLOW}⚠ Server returned HTTP $HTTP_CODE${NC}"
    fi
else
    echo -e "${YELLOW}⚠ curl not found, skipping connectivity test${NC}"
fi

# Step 5: Configuration summary
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Configuration Summary${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

echo -e "${GREEN}✓ Backend:${NC} critical-fuchsia-ape"
echo -e "${GREEN}✓ API URL:${NC} $API_URL"
echo -e "${GREEN}✓ API Key:${NC} ${API_KEY:0:10}...${API_KEY: -10}"
echo -e "${GREEN}✓ .env file:${NC} $ENV_FILE"

# Step 6: Show how to start the server
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Next Steps${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

echo -e "${YELLOW}1. Start the MCP server:${NC}"
echo -e "   ${BLUE}cd $PROJECT_ROOT${NC}"
echo -e "   ${BLUE}python3 devskyy_mcp.py${NC}"

echo -e "\n${YELLOW}2. Or run with environment variables:${NC}"
echo -e "   ${BLUE}export MCP_BACKEND=critical-fuchsia-ape${NC}"
echo -e "   ${BLUE}export CRITICAL_FUCHSIA_APE_URL=$API_URL${NC}"
echo -e "   ${BLUE}export CRITICAL_FUCHSIA_APE_KEY=$API_KEY${NC}"
echo -e "   ${BLUE}python3 devskyy_mcp.py${NC}"

echo -e "\n${YELLOW}3. Use with Claude Desktop:${NC}"
echo -e "   Add to ~/.claude/extensions.json or claude_desktop_config.json"
echo -e "   See docs/CRITICAL_FUCHSIA_APE_SETUP.md for details"

echo -e "\n${YELLOW}4. Verify tools are available:${NC}"
echo -e "   ${BLUE}python3 devskyy_mcp.py | grep 'Tools Available'${NC}"

echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Setup complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

# Optional: Ask if user wants to start the server now
read -p "Start the MCP server now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "\n${BLUE}Starting DevSkyy MCP server...${NC}\n"
    cd "$PROJECT_ROOT"
    python3 devskyy_mcp.py
fi
