#!/usr/bin/env python3
"""Sync brand.yaml → wordpress-theme/skyyrose-flagship/inc/brand.generated.php.

Reads `assets/brand/brand.yaml` and emits a PHP constants + helper-functions
file the WordPress theme includes. Do NOT edit the generated .php file — edit
brand.yaml and re-run this script.

Usage:
    python scripts/sync_brand_to_php.py
    python scripts/sync_brand_to_php.py --check       # exit 1 if php file is stale
    python scripts/sync_brand_to_php.py --output /tmp/brand.generated.php
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from skyyrose.elite_studio.brand import BrandConfig  # noqa: E402

DEFAULT_OUTPUT = (
    _REPO_ROOT / "wordpress-theme" / "skyyrose-flagship" / "inc" / "brand.generated.php"
)


def _php_string(s: str) -> str:
    """PHP-single-quoted string. Escapes ' and \\."""
    escaped = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _php_array(items: list | tuple) -> str:
    inner = ", ".join(_php_string(str(x)) for x in items)
    return f"[{inner}]"


def build_php(brand: BrandConfig) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    out: list[str] = []
    out.append("<?php")
    out.append("/**")
    out.append(" * SkyyRose Brand Constants — AUTO-GENERATED.")
    out.append(" *")
    out.append(" * Source of truth: assets/brand/brand.yaml")
    out.append(" * Generator:       scripts/sync_brand_to_php.py")
    out.append(f" * Generated:       {now}")
    out.append(" *")
    out.append(" * DO NOT EDIT THIS FILE. Edit brand.yaml and re-run the generator.")
    out.append(" */")
    out.append("")
    out.append("if ( ! defined( 'ABSPATH' ) ) { exit; }")
    out.append("")
    out.append("// ─── Tagline ────────────────────────────────────────────────────────")
    out.append(f"define( 'SKYYROSE_BRAND_TAGLINE', {_php_string(brand.tagline_active)} );")
    out.append(
        f"define( 'SKYYROSE_RETIRED_TAGLINES', {_php_array(list(brand.retired_taglines))} );"
    )
    out.append("")

    # Identity
    out.append("// ─── Brand identity ─────────────────────────────────────────────────")
    ident = brand.identity
    for key, const in (
        ("name", "SKYYROSE_BRAND_NAME"),
        ("legal_name", "SKYYROSE_LEGAL_NAME"),
        ("founder", "SKYYROSE_BRAND_FOUNDER"),
        ("origin", "SKYYROSE_BRAND_ORIGIN"),
    ):
        val = str(ident.get(key) or "")
        if val:
            out.append(f"define( '{const}', {_php_string(val)} );")
    mission = str(ident.get("mission") or "").strip()
    if mission:
        out.append(f"define( 'SKYYROSE_BRAND_MISSION', {_php_string(mission)} );")
    out.append("")

    # Primary colors (flat constants for easy CSS/PHP use)
    out.append("// ─── Color palette ──────────────────────────────────────────────────")
    primary = brand.colors.get("primary") or {}
    mapping = {
        "dark": "SKYYROSE_COLOR_DARK",
        "rose_gold": "SKYYROSE_COLOR_ROSE_GOLD",
        "gold": "SKYYROSE_COLOR_GOLD",
        "crimson": "SKYYROSE_COLOR_CRIMSON",
        "silver": "SKYYROSE_COLOR_SILVER",
    }
    for key, const in mapping.items():
        if key in primary:
            out.append(f"define( '{const}', {_php_string(primary[key])} );")
    out.append("")

    # URLs
    out.append("// ─── URLs ───────────────────────────────────────────────────────────")
    for key, val in brand.urls.items():
        const = f"SKYYROSE_URL_{key.upper()}"
        out.append(f"define( '{const}', {_php_string(str(val))} );")
    out.append("")

    # Collections (emitted as a helper function returning an array)
    out.append("// ─── Collections ────────────────────────────────────────────────────")
    out.append("if ( ! function_exists( 'skyyrose_brand_collections' ) ) {")
    out.append("    function skyyrose_brand_collections() {")
    out.append("        return [")
    for slug, cb in brand.collections.items():
        out.append(f"            {_php_string(slug)} => [")
        out.append(f"                'display_name'    => {_php_string(cb.display_name)},")
        out.append(f"                'tagline'         => {_php_string(cb.tagline)},")
        out.append(f"                'description'     => {_php_string(cb.description)},")
        out.append(f"                'theme'           => {_php_string(cb.theme)},")
        out.append(f"                'mood'            => {_php_string(cb.mood)},")
        out.append(f"                'inspiration'     => {_php_string(cb.inspiration)},")
        out.append(f"                'hero_scene'      => {_php_string(cb.hero_scene)},")
        out.append(f"                'target_audience' => {_php_string(cb.target_audience)},")
        out.append("                'palette'         => [")
        for pkey, pval in cb.palette.items():
            out.append(f"                    {_php_string(pkey)} => {_php_string(pval)},")
        out.append("                ],")
        out.append("            ],")
    out.append("        ];")
    out.append("    }")
    out.append("}")
    out.append("")

    # Social handles
    out.append("// ─── Social handles ─────────────────────────────────────────────────")
    out.append("if ( ! function_exists( 'skyyrose_social_handles' ) ) {")
    out.append("    function skyyrose_social_handles() {")
    out.append("        return [")
    for k, v in brand.social.items():
        out.append(f"            {_php_string(k)} => {_php_string(str(v))},")
    out.append("        ];")
    out.append("    }")
    out.append("}")
    out.append("")

    # JSON-LD organization schema helper (for SEO)
    out.append("// ─── JSON-LD Organization schema (for SEO) ──────────────────────────")
    social_list_json = json.dumps([str(v) for v in brand.social.values() if v], ensure_ascii=False)
    out.append("if ( ! function_exists( 'skyyrose_json_ld_organization' ) ) {")
    out.append("    function skyyrose_json_ld_organization() {")
    out.append("        return [")
    out.append("            '@context'    => 'https://schema.org',")
    out.append("            '@type'       => 'Organization',")
    out.append("            'name'        => SKYYROSE_BRAND_NAME,")
    out.append("            'legalName'   => SKYYROSE_LEGAL_NAME,")
    out.append("            'founder'     => SKYYROSE_BRAND_FOUNDER,")
    out.append("            'slogan'      => SKYYROSE_BRAND_TAGLINE,")
    out.append("            'url'         => SKYYROSE_URL_FLAGSHIP,")
    out.append(
        "            'sameAs'      => array_values( array_filter( skyyrose_social_handles() ) ),"
    )
    out.append("        ];")
    out.append("    }")
    out.append("}")
    out.append("")

    out.append("// End of auto-generated file.")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 without writing if output would change"
    )
    args = parser.parse_args(argv)

    brand = BrandConfig.load()
    content = build_php(brand)

    if args.check:
        if not args.output.is_file():
            print(
                f"ERROR: {args.output.relative_to(_REPO_ROOT)} missing — run without --check to create"
            )
            return 1
        current = args.output.read_text()

        # Ignore the timestamp line when comparing
        def _strip_ts(s: str) -> str:
            return "\n".join(
                line for line in s.splitlines() if not line.strip().startswith("* Generated:")
            )

        if _strip_ts(current) == _strip_ts(content):
            print(f"OK: {args.output.relative_to(_REPO_ROOT)} is in sync with brand.yaml")
            return 0
        print(f"DIFF: {args.output.relative_to(_REPO_ROOT)} would change — re-run without --check")
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(
        f"Wrote {args.output.relative_to(_REPO_ROOT)} "
        f"({len(content):,} bytes, {len(brand.collections)} collections)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
