ml_pipeline:
  name: "Fashion Design ML Pipeline"
  version: "1.0.0"

stages:
  collect:
    enabled: true
    input_paths:
      - "./data/designs/raw"
    file_patterns:
      - "*.jpg"
      - "*.png"
      - "*.jpeg"
    batch_size: 32

  validate:
    enabled: true
    checks:
      - "file_integrity"
      - "naming_pattern"
      - "metadata_completeness"
    validation_rules:
      min_resolution: [512, 512]
      max_file_size_mb: 10
      required_metadata:
        - "style"
        - "color"
        - "season"

  feature_extract:
    enabled: true
    model: "clip"
    model_config:
      name: "ViT-B/32"
      device: "cuda"
    embedding_dim: 512
    output_path: "./data/designs/processed/embeddings"

  generate:
    enabled: true
    model: "diffusion"
    model_config:
      name: "runwayml/stable-diffusion-v1-5"
      device: "cuda"
      guidance_scale: 7.5
      num_inference_steps: 50
    batch_size: 4
    output_path: "./data/designs/processed/generated"

  evaluate:
    enabled: true
    metrics:
      - "novelty_score"
      - "similarity_threshold"
      - "quality_score"
    thresholds:
      min_novelty: 0.6
      max_similarity: 0.85
      min_quality: 0.7

  store:
    enabled: true
    output_path: "./data/designs/processed"
    format: "png"
    metadata_format: "json"
    trigger_commerce_agent: true

models:
  clip:
    model_name: "ViT-B/32"
    pretrained: true
    cache_dir: "./models/clip"

  diffusion:
    model_name: "runwayml/stable-diffusion-v1-5"
    pretrained: true
    cache_dir: "./models/diffusion"
    safety_checker: true

  stylegan:
    model_name: "stylegan2-ffhq"
    pretrained: true
    cache_dir: "./models/stylegan"

hardware:
  device: "cuda"  # or "cpu"
  mixed_precision: true
  num_workers: 4
  pin_memory: true

performance:
  max_batch_size: 32
  prefetch_factor: 2
  persistent_workers: true
