queue:
  backend: "redis"
  prefix: "fashion_ai"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  max_connections: 50

channels:
  designer_to_commerce:
    description: "Design completion to product listing"
    priority: "high"
    retention: 3600

  commerce_to_marketing:
    description: "Product listings to marketing campaigns"
    priority: "medium"
    retention: 7200

  marketing_to_finance:
    description: "Campaign performance to financial tracking"
    priority: "medium"
    retention: 7200

  finance_to_ops:
    description: "Financial events to ops monitoring"
    priority: "low"
    retention: 10800

  ops_broadcast:
    description: "System-wide notifications"
    priority: "critical"
    retention: 86400

message_schema:
  required_fields:
    - "id"
    - "source_agent"
    - "target_agent"
    - "task_type"
    - "payload"
    - "timestamp"
  optional_fields:
    - "priority"
    - "retry_count"
    - "correlation_id"

routing:
  task_types:
    generate_design: "designer"
    list_sku: "commerce"
    announce: "marketing"
    record_ledger: "finance"
    health_check: "ops"

performance:
  max_queue_depth: 10000
  message_timeout: 300
  batch_size: 100
  poll_interval: 1.0

monitoring:
  enable_metrics: true
  metrics_interval: 60
  alert_thresholds:
    queue_depth_warning: 1000
    queue_depth_critical: 5000
    latency_warning_ms: 1000
    latency_critical_ms: 5000
